In [1]:
import torch
import numpy as np
import torch.nn as nn

# 1. torch.tensor()/torch.Tensor()

In [ ]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.Tensor([1, 2, 3])

tensor([1., 2., 3.])

In [ ]:
torch.Tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
list1 = [[1, 2, 3], [4, 5, 6]]
list2 = [[1, 2, 3], [4, 5, 6]]

torch.Tensor((list1, list2))

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

# 2. torch.from_numpy()

In [ ]:
array = np.array([1, 2, 3])

torch.from_numpy(array)

tensor([1, 2, 3])

In [ ]:
torch.from_numpy(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

# 3. torch.rand()

In [ ]:
torch.rand((4, ))

tensor([0.2850, 0.5590, 0.6600, 0.6660])

In [ ]:
torch.rand((3, 4)) # 2D

tensor([[0.3499, 0.6893, 0.0377, 0.0150],
        [0.5514, 0.3862, 0.4897, 0.1769],
        [0.7210, 0.7848, 0.3463, 0.7255]])

In [ ]:
torch.rand((3, 2, 4))

tensor([[[0.0019, 0.2724, 0.4669, 0.0207],
         [0.9908, 0.7979, 0.0541, 0.1274]],

        [[0.0249, 0.3039, 0.3127, 0.4761],
         [0.3788, 0.4697, 0.2553, 0.4115]],

        [[0.2332, 0.0906, 0.4259, 0.1337],
         [0.0243, 0.5883, 0.5215, 0.0266]]])

In [ ]:
torch.rand((16, 3, 128, 128)).size()

torch.Size([16, 3, 128, 128])

# 3. torch.randn()

In [ ]:
torch.randn((2, )) # 1D

tensor([1.0260, 0.2438])

In [ ]:
torch.randn((3, 4)) # 2D

tensor([[-0.0866, -0.5227,  1.1566,  0.7062],
        [ 2.2518,  0.4340, -0.8353,  0.7809],
        [-1.1123,  0.1841, -0.0112,  0.5317]])

In [ ]:
torch.randn((2, 2, 4)) # 3D

tensor([[[-0.4910,  1.0399, -1.5044, -2.2785],
         [-0.7280, -0.3413, -0.1099,  0.2544]],

        [[-0.0784,  0.3125, -1.6391, -1.0656],
         [ 0.3892, -0.7178, -0.2287,  0.7575]]])

In [ ]:
torch.randn((16, 3, 128, 128)).size() # ND

torch.Size([16, 3, 128, 128])

# 4. torch.randint()

In [ ]:
torch.randint(0, 10, (4, )) # 1D

tensor([5, 7, 7, 2])

In [ ]:
torch.randint(0, 10, (3, 4))

tensor([[3, 0, 8, 5],
        [3, 3, 8, 4],
        [3, 6, 2, 3]])

In [ ]:
torch.randint(0, 10, (2, 3, 4)) # 3D

tensor([[[9, 8, 4, 4],
         [3, 0, 9, 5],
         [0, 5, 5, 5]],

        [[4, 9, 3, 5],
         [2, 9, 8, 5],
         [2, 5, 3, 7]]])

In [ ]:
torch.randint(0, 10, (16, 3, 128, 128)).size()

torch.Size([16, 3, 128, 128])

# 5. torch.max()

In [ ]:
torch.max(torch.randint(0, 10, (2, 3)))

tensor(9)

In [ ]:
value, _ = torch.max(torch.randint(0, 100, (16, 3, 20, 20)), dim = 0)

value.size()

torch.Size([3, 20, 20])

In [ ]:
value, _ = torch.max(torch.randint(0, 100, (16, 3, 20, 20)), dim = 1)

value.size()

torch.Size([16, 20, 20])

In [ ]:
value, _ = torch.max(torch.randint(0, 100, (16, 3, 20, 20)), dim = 2)

value.size()

torch.Size([16, 3, 20])

In [ ]:
value, _ = torch.max(torch.randint(0, 100, (16, 3, 20, 20)), dim = -1)

value.size()

torch.Size([16, 3, 20])

# 6. torch.min()

In [ ]:
torch.min(torch.randn(4, ))

tensor(-1.1934)

In [ ]:
value, idicies = torch.min(torch.randn((3, 4)), dim = 0) # Column wise -> the result shape would be 4

print(value.size())

value, idicies = torch.min(torch.randn((3, 4)), dim = 1) # ROW wise -> the result shape would be 3

print(value.size())

torch.Size([4])
torch.Size([3])


In [ ]:
value, indicies = torch.min(torch.randn((2, 3, 4)), dim = 0)

print(value.size()) # It would be print (3, 4)

value, indicies = torch.min(torch.randn((2, 3, 4)), dim = 1)

print(value.size()) # It will print (2, 4)

value, indicies = torch.min(torch.randn((2, 3, 4)), dim = 2)

print(value.size()) # It will print (2, 3)

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])


# 7. torch.mean()

In [ ]:
torch.mean(torch.randn((2, )))

tensor(-0.4021)

In [ ]:
torch.mean(torch.randn((3, 4)))

tensor(-0.2171)

In [ ]:
torch.mean(torch.randint(0, 10, (16, 3, 128, 128)), dtype = torch.float)

tensor(4.4946)

In [ ]:
torch.mean(torch.randint(0, 10, (16, 3, 128, 128)), dtype = torch.float, dim = 0).size() # It will print -> (3, 128, 128)

torch.Size([3, 128, 128])

In [ ]:
torch.mean(torch.randint(0, 10, (16, 3, 128, 128)), dtype = torch.float, dim = 1).size() # It will print -> (16, 128, 128)

torch.Size([16, 128, 128])

In [ ]:
torch.mean(torch.randint(0, 10, (16, 3, 128, 128)), dtype = torch.float, dim = 2).size() # It will print -> (16, 3, 128)

torch.Size([16, 3, 128])

In [ ]:
torch.mean(torch.randint(0, 10, (16, 3, 128, 128)), dtype = torch.float, dim = 3).size() # It will print -> (16, 3, 128)

torch.Size([16, 3, 128])

# 8. torch.median()

In [ ]:
torch.median(torch.randn((2, )))

tensor(-0.2132)

In [ ]:
value, _ = torch.median(torch.rand((3, 4)), dim = 0) # -> It will print : 4
value.size()

torch.Size([4])

In [ ]:
value, _ = torch.median(torch.rand((3, 4)), dim = 1) # -> It will print : 3
value.size()

torch.Size([3])

# 9. torch.std()

In [ ]:
torch.std(torch.randn(2, ))

tensor(0.7701)

In [ ]:
torch.std(torch.randn((2, 3)), dim = 0).size() # It will print: 3

torch.Size([3])

In [ ]:
torch.std(torch.randn((2, 3)), dim = 1).size() # It will print: 2

torch.Size([2])

In [ ]:
torch.std(torch.randn((16, 3, 128, 128)),dim = 0).size() # 3, 128, 128

torch.Size([3, 128, 128])

In [ ]:
torch.std(torch.randn((16, 3, 128, 128)),dim = 1).size() # 16, 128, 128

torch.Size([16, 128, 128])

In [ ]:
torch.std(torch.randn((16, 3, 128, 128)),dim = 2).size() # 16,3, 128

torch.Size([16, 3, 128])

In [ ]:
torch.std(torch.randn((16, 3, 128, 128)),dim = 3).size() # 16,3, 128

torch.Size([16, 3, 128])

# 10.torch.var()

In [ ]:
torch.var(torch.randn((3, )))

tensor(1.6165)

In [ ]:
torch.var(torch.randn((3, 4)), dim = 0).size() # It will print: 4

torch.Size([4])

In [ ]:
torch.var(torch.randn((3, 4)), dim = 1).size() # It will print: 3

torch.Size([3])

In [ ]:
torch.var(torch.randn((16, 3, 128, 128)), dim = 0).size() # It will return 3, 128, 128

torch.Size([3, 128, 128])

In [ ]:
torch.var(torch.randn((16, 3, 128, 128)), dim = 1).size() # It will return 16, 128, 128

torch.Size([16, 128, 128])

In [ ]:
torch.var(torch.randn((16, 3, 128, 128)), dim = 2).size() # It will return 16, 3, 128

torch.Size([16, 3, 128])

In [ ]:
torch.var(torch.randn((16, 3, 128, 128)), dim = 3).size() # It will return 16, 3, 128

torch.Size([16, 3, 128])

# 11. torch.max()

In [ ]:
for index in range(4):
  print(torch.randn((16, 3, 128, 128)).max(dim = index)[0].size())

torch.Size([3, 128, 128])
torch.Size([16, 128, 128])
torch.Size([16, 3, 128])
torch.Size([16, 3, 128])


# 12. torch.size()

In [ ]:
torch.randint(0, 10, (4, )).size()

torch.Size([4])

In [ ]:
torch.randn((3, 4)).size()

torch.Size([3, 4])

In [ ]:
torch.randn((3, 4)).size(0), torch.randn((3, 4)).size(1)

(3, 4)

In [ ]:
torch.randn((16, 3, 128, 128)).size()

torch.Size([16, 3, 128, 128])

In [ ]:
torch.randn((16, 3, 128, 128)).size()[0]

16

In [ ]:
print(torch.randn((16, 3, 128, 128)).size()[1])
print(torch.randn((16, 3, 128, 128)).size()[2])
print(torch.randn((16, 3, 128, 128)).size()[3])

3
128
128


#13. torch.shape/[]

In [ ]:
torch.randn((3, )).shape

torch.Size([3])

In [ ]:
torch.randn((3, 4)).shape

torch.Size([3, 4])

In [ ]:
torch.randn(64, 3, 128, 128).shape

torch.Size([64, 3, 128, 128])

In [ ]:
print(torch.randint(0, 10, (4, 5, 128, 128)).shape[0])
print(torch.randint(0, 10, (4, 5, 128, 128)).shape[1])
print(torch.randint(0, 10, (4, 5, 128, 128)).shape[2])
print(torch.randint(0, 10, (4, 5, 128, 128)).shape[3])

4
5
128
128


# 14. torch.view()/-1

In [ ]:
torch.randn((3, 4)).view(-1) # 1D

tensor([-0.1356, -0.3542, -1.0624, -1.0706, -1.2918, -0.7297, -1.8199,  0.0424,
        -1.1206, -1.8227,  0.8953,  0.3168])

In [ ]:
torch.randn((3, 4)).view(4, 3).size() # (4, 3)

torch.Size([4, 3])

In [ ]:
A = torch.randn((16, 3, 128, 128))

print(A.size())

print(A.view(A.size(0), A.size(2), A.size(3), -1).size()) # (16, 128, 128, 3)

print(A.view(16, 128, 128, -1).size())

torch.Size([16, 3, 128, 128])
torch.Size([16, 128, 128, 3])
torch.Size([16, 128, 128, 3])


# 15. torch.reshape()

In [ ]:
torch.randn((3, 4)).reshape(-1).size() # 1D

torch.Size([12])

In [ ]:
torch.randn((3, 4)).reshape(4, -1).size() # (4, 3)

torch.Size([4, 3])

In [ ]:
torch.randn((16, 3, 128, 128)).reshape(16, 3, -1).view(-1, 3, 128, 128).size() # (16, 3, 128, 128)

torch.Size([16, 3, 128, 128])

# 16. torch.cat(dim = 0/1)

In [ ]:
A = torch.randn((3, 4))
B = torch.randn((3, 60))

torch.cat((A, B), dim = 1).size() # (3, 64)

torch.Size([3, 64])

In [ ]:
A = torch.randn((3, 60))
B = torch.randn((3, 60))

torch.cat((A, B), dim = 0).size() # (3, 120)

torch.Size([6, 60])

In [ ]:
A = torch.randn((16, 3, 128, 128))
B = torch.randn((16, 3, 128, 128))

torch.cat((A, B), dim = 1).size() # (16, 6, 128, 128)

torch.Size([16, 6, 128, 128])

In [ ]:
A = torch.randn((16, 3, 128, 128))
B = torch.randn((16, 3, 128, 128))

torch.cat((A, B), dim = 0).size() # (32, 3, 128, 128)

torch.Size([32, 3, 128, 128])

# 17. torch.linespace() -> 1D?

In [ ]:
torch.linspace(0, 10, 20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

# 18. torch.logspace() -> 1D?


In [ ]:
torch.logspace(0, 10, 20)

tensor([1.0000e+00, 3.3598e+00, 1.1288e+01, 3.7927e+01, 1.2743e+02, 4.2813e+02,
        1.4384e+03, 4.8329e+03, 1.6238e+04, 5.4556e+04, 1.8330e+05, 6.1585e+05,
        2.0691e+06, 6.9519e+06, 2.3357e+07, 7.8476e+07, 2.6367e+08, 8.8587e+08,
        2.9764e+09, 1.0000e+10])

# 19. torch.arange()

In [ ]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.arange(0, 10, 20)

tensor([0])

# 20 torch.flatten()

In [ ]:
torch.flatten(torch.randn((3, 4))).size() # 12

torch.Size([12])

In [ ]:
torch.flatten(torch.randn((16, 3, 128, 128))).size()

torch.Size([786432])

In [ ]:
torch.randn((16, 3, 128, 128)).view(-1).size()

torch.Size([786432])

# 21. torch.zeros()

In [ ]:
torch.zeros((3, ))

tensor([0., 0., 0.])

In [ ]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.zeros((16, 3, 128, 128)).size() # (16, 3, 128, 128)

torch.Size([16, 3, 128, 128])

# 22. torch.ones()

In [ ]:
torch.ones((3, ))

tensor([1., 1., 1.])

In [ ]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.ones((16, 3, 128, 128)).size()

torch.Size([16, 3, 128, 128])

# 23. torch.ones_like()

In [ ]:
torch.ones_like(torch.randint(0, 10, (4, 5))).size() # (4, 5)

torch.Size([4, 5])

In [ ]:
torch.ones_like(torch.randn((16, 3, 128, 128))).size()

torch.Size([16, 3, 128, 128])

# 24. torch.zeros_like()

In [ ]:
torch.zeros_like(torch.randint(0, 10, (3, 4))).size() # (3, 4)

torch.Size([3, 4])

In [ ]:
torch.zeros_like(torch.randint(0, 10, (3, 4, 128))).size() # (3, 4, 128)

torch.Size([3, 4, 128])

# 25. torch.full()

In [ ]:
torch.full((4, ), 0.00001)

tensor([1.0000e-05, 1.0000e-05, 1.0000e-05, 1.0000e-05])

In [ ]:
torch.full((3, 4), 1e-10)

tensor([[1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10],
        [1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10],
        [1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10]])

In [ ]:
torch.full((64, 3, 128, 128), -1e2).size()

torch.Size([64, 3, 128, 128])

# 26. torch.pow()

In [ ]:
array = torch.randn((3, 4))

array = array.unsqueeze(0).unsqueeze(1)

array = array.view(array.size(2), array.size(3), array.size(0), -1)

torch.pow(array, 1e2).view(3, 4)

tensor([[1.6932e+16, 8.5553e-09, 1.0442e-13, 1.1112e-18],
        [1.1917e+23, 0.0000e+00, 4.3070e-26, 0.0000e+00],
        [8.0379e+03, 3.1059e-22, 2.2199e-08, 2.9654e-37]])

# 27. torch.unbind()

In [ ]:
torch.randn((3, 4)).unbind()

(tensor([-0.4977,  0.5230,  0.0032, -1.2226]),
 tensor([-1.6497, -1.0003, -0.1340,  0.2897]),
 tensor([1.0764, 0.2958, 1.2764, 0.0625]))

In [ ]:
print(torch.randn((3, 4)).unbind()[0])
print(torch.randn((3, 4)).unbind()[1])
print(torch.randn((3, 4)).unbind()[2])

tensor([ 0.2065,  0.9993, -2.3691,  0.2010])
tensor([-0.8578,  0.8737,  0.5324, -0.8851])
tensor([-0.5355, -0.5456,  0.8180, -1.6136])


# 28. torch.tile()

In [ ]:
torch.randn((3, 4)).tile(2, 16).size() # (6, 64)

torch.Size([6, 64])

In [ ]:
torch.randn((64, 1, 128, 128)).tile(1, 3, 1, 1).size() # (64, 3, 128, 128)

torch.Size([64, 3, 128, 128])

# 29.torch.unsqueeze()/INDEX

In [ ]:
torch.randn(16, 128, 128).unsqueeze(1).size() # (16, 1, 128, 128)

torch.Size([16, 1, 128, 128])

In [ ]:
torch.randn((64, )).unsqueeze(0).unsqueeze(1).unsqueeze(2).size() # (1, 1, 1, 128)

torch.Size([1, 1, 1, 64])

# 30. torch.squeeze()

In [ ]:
torch.randn((16, 1, 128, 128)).squeeze().size() # Remove 1

torch.Size([16, 128, 128])

In [ ]:
torch.randn((1, 1, 128, 128, 1)).squeeze().size() # (128, 128)

torch.Size([128, 128])

# 31. torch.eye()

In [ ]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# 32. torch.where()

In [ ]:
A = torch.randint(0, 10, (3, 4))
torch.where(A > 8, 1e2, A)

tensor([[  2.,   2.,   0.,   1.],
        [  1.,   2.,   4.,   8.],
        [100.,   0.,   3.,   1.]])

In [ ]:
torch.where(A>5, 0.001, 0)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0010],
        [0.0010, 0.0000, 0.0000, 0.0000]])

# 33. torch.transpose(dim = 0/1/2)/t()

In [ ]:
torch.randn((3, 4)).t().size() # (4, 3)

torch.Size([4, 3])

In [ ]:
torch.randn((16, 3, 128, 128)).transpose(1, -1).size() # (16, 128, 128, 3)

torch.Size([16, 128, 128, 3])

# 34. torch.hstack()

In [ ]:
A1 = torch.randn((3, 4))
A2 = torch.randn((3, 4))

torch.hstack((A1, A2)).size() # (3, 8)

torch.Size([3, 8])

# 35. torch.vstack()

In [ ]:
A1 = torch.randn((3, 4))
A2 = torch.randn((3, 4))

torch.vstack((A1, A2)).size() # (6, 4)

torch.Size([6, 4])

# 36. torch.maxpool2D()

In [2]:
torch.max_pool2d(torch.randn((16, 3, 128, 128)), kernel_size=2, stride=2).size() # (16, 3, 64, 64)

torch.Size([16, 3, 64, 64])

In [3]:
A = nn.MaxPool2d(kernel_size=2, stride=2)

A(torch.randn((16, 3, 128, 128))).size() # (16, 3, 64, 64)

torch.Size([16, 3, 64, 64])

# 37. Torch.Sigmoid()

In [4]:
torch.sigmoid(torch.randn((64, 4))).size() # (64, 4)

torch.Size([64, 4])

In [5]:
A = nn.Sigmoid()

A(torch.randn((64, 4))).size() # (64, 4)

torch.Size([64, 4])

In [6]:
A = nn.Sigmoid()

torch.where(A(torch.randn(4, 4))>0.5, 1, 0)

tensor([[0, 0, 1, 0],
        [1, 1, 1, 1],
        [0, 1, 0, 1],
        [1, 1, 1, 0]])

# 38. torch.softamax()

In [7]:
torch.softmax(torch.randn((16, 4)), dim = 1).size() # (16, 4)

torch.Size([16, 4])

In [8]:
A = nn.Softmax(dim = 1)

A(torch.randn((16, 4))).size() # (16, 4)

torch.Size([16, 4])

In [14]:
A = nn.Softmax(dim = 1)

torch.argmax(A(torch.randn((16, 4))), dim = 1) # ROW WISE - > 16

tensor([3, 3, 2, 2, 0, 2, 1, 1, 1, 2, 1, 3, 3, 1, 2, 0])

# 39. torch.norm(dim = 0/1/ND)

In [15]:
torch.norm(torch.randn((4, 4)), dim = 1) # ROW WISE -> 4

tensor([2.5904, 2.2807, 1.4130, 1.9226])

In [16]:
torch.norm(torch.randn((16, 32)), dim = 0).size() # Column wise -> 32

torch.Size([32])

In [17]:
torch.norm(torch.randn((16, 3, 128, 128)), dim = 0).size() # (3, 128, 128)

torch.Size([3, 128, 128])

In [18]:
torch.norm(torch.randn((16, 3, 128, 128)), dim = 1).size() # (16, 128, 128)

torch.Size([16, 128, 128])

In [19]:
torch.norm(torch.randn((16, 3, 128, 128)), dim = 2).size() # (16, 3, 128)

torch.Size([16, 3, 128])

In [20]:
torch.norm(torch.randn((16, 3, 128, 128)), dim = 3).size() # (16, 3, 128)

torch.Size([16, 3, 128])

# 40. torch.abs()

In [21]:
torch.abs(torch.randn((16, 64)) - torch.randn((16, 64))).size() # (16, 64)

torch.Size([16, 64])

In [22]:
torch.abs(torch.randn((16, 64)) - torch.randn((64, ))).size() # Do the broadcasting and return (16, 64)

torch.Size([16, 64])

In [24]:
torch.abs(torch.randn((16, 3, 128, 128)) - torch.randn((16, 3, 128, 128))).mean() # 1D -> Tensor

tensor(1.1272)

# 41. torch.permute()

In [25]:
torch.randn((16, 3, 128, 128)).permute(0, 2, 3, 1).size() # (16, 128, 128, 3)

torch.Size([16, 128, 128, 3])

In [26]:
torch.randn((16, 3, 128, 128)).view(16, 128, 128, 3).size() # (16, 128, 128, 3)

torch.Size([16, 128, 128, 3])

In [27]:
torch.randn((16, 3, 128, 128)).transpose(1, -1).size() # (16, 128, 128, 3)

torch.Size([16, 128, 128, 3])

# 42. torch.argmax(dim = 0/1)

In [29]:
torch.argmax(torch.randn((64, 4)), dim = 1).size() # ROW - > the result would be: 64

torch.Size([64])

In [31]:
torch.argmax(torch.randn((64, 4)), dim = 0).size() # Column - > the result would be: 4

torch.Size([4])

In [33]:
torch.argmax(torch.randn((16, 3, 128, 128)), dim = 0).size() # the result would be: 3, 128, 128

torch.Size([3, 128, 128])

In [34]:
torch.argmax(torch.randn((16, 3, 128, 128)), dim = 1).size() # the result would be: 16, 128, 128

torch.Size([16, 128, 128])

In [35]:
torch.argmax(torch.randn((16, 3, 128, 128)), dim = 2).size() # the result would be: 16, 3, 128

torch.Size([16, 3, 128])

In [37]:
torch.argmax(torch.randn((16, 3, 128, 128)), dim = 3).size() # the result would be: 16, 3, 128

torch.Size([16, 3, 128])

# 43. torch.argmin(dim = 0/1/ND)

In [38]:
torch.argmin(torch.randn((64, 4)), dim = 1).size() # (64)

torch.Size([64])

In [39]:
torch.argmin(torch.randn((128, 4)), dim = 0).size() # (4)

torch.Size([4])

In [41]:
torch.argmin(torch.randn((16, 3, 128, 128)), dim = 0).size() # (3, 128, 128)

torch.Size([3, 128, 128])

In [42]:
torch.argmin(torch.randn((16, 3, 128, 128)), dim = 1).size() # (16, 128, 128)

torch.Size([16, 128, 128])

In [43]:
torch.argmin(torch.randn((16, 3, 128, 128)), dim = 2).size() # (16, 3, 128)

torch.Size([16, 3, 128])

In [44]:
torch.argmin(torch.randn((16, 3, 128, 128)), dim = 3).size() # (16, 3, 128)

torch.Size([16, 3, 128])

# 44. torch.sort(descending = True)

In [46]:
value, _ = torch.sort(torch.randint(0, 10, (3, 4)), descending=False)
value.size()

torch.Size([3, 4])

In [47]:
value, _ = torch.sort(torch.randint(0, 10, (3, 4)), descending=True)
value.size()

torch.Size([3, 4])

In [51]:
value, _ = torch.sort(torch.randint(0, 10, (3, 4)), descending=False, dim = 0) # Column wise: the result is: 4
value.size()

torch.Size([3, 4])

#45. torch.embeddings()

In [57]:
A = nn.Embedding(num_embeddings=20, embedding_dim=128)

A(torch.randint(0, 20, (64, 200))).size() # (64, 200, 128)

torch.Size([64, 200, 128])

# 46. torch.upsample()

In [58]:
A = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=True)

A(torch.randn((16, 3, 64, 64))).size() # (16, 3, 128, 128)

torch.Size([16, 3, 128, 128])

In [59]:
A = nn.Upsample(scale_factor=4, mode = "bilinear", align_corners=True)


A(torch.randn((16, 3, 64, 64))).size() # (16, 3, 256, 256)

torch.Size([16, 3, 256, 256])

# 47. nn.PixelShuffle()

In [60]:
A = nn.PixelShuffle(upscale_factor=2)

A(torch.randn((16, 64, 128, 128))).size() # (16, 16, 256, 256)

torch.Size([16, 16, 256, 256])

In [61]:
A = nn.PixelShuffle(upscale_factor=4)

A(torch.randn((16, 64, 128, 128))).size() # (16, 4, 512, 512)

torch.Size([16, 4, 512, 512])

# 48. torch.chunk(input = tensor)

In [65]:
chunk1, chunk2, chunk3, chunk4 =  torch.chunk(torch.randn((16, 3, 64, 64)), chunks=4, dim = -1) # (16, 3, 64, 16) * 4 times

print(chunk1.size(), chunk2.size(), chunk3.size(), chunk4.size())

torch.Size([16, 3, 64, 16]) torch.Size([16, 3, 64, 16]) torch.Size([16, 3, 64, 16]) torch.Size([16, 3, 64, 16])


In [66]:
chunk1, chunk2, chunk3, chunk4 =  torch.chunk(torch.randn((16, 16, 64, 64)), chunks=4, dim = 1) # (16, 4, 64, 64) * 4 times

print(chunk1.size(), chunk2.size(), chunk3.size(), chunk4.size())

torch.Size([16, 4, 64, 64]) torch.Size([16, 4, 64, 64]) torch.Size([16, 4, 64, 64]) torch.Size([16, 4, 64, 64])


# 49. torch.triu()

In [67]:
torch.triu(torch.randn((3, 4)), diagonal=0)

tensor([[ 0.0626,  0.6226,  1.2958, -0.4963],
        [ 0.0000, -0.7367,  0.3011,  0.8339],
        [ 0.0000,  0.0000, -1.1067,  1.5820]])

In [68]:
torch.triu(torch.randn((3, 4)), diagonal=1)

tensor([[ 0.0000,  1.9901,  0.3975,  0.7013],
        [ 0.0000,  0.0000,  1.1758, -3.1144],
        [ 0.0000,  0.0000,  0.0000,  0.0916]])

# 50. torch.masked_fill()

In [74]:
A = torch.randint(0, 5, (5, 4))

torch.masked_fill(A, A == 1, 100)

tensor([[100,   4,   4,   4],
        [  0,   2, 100,   3],
        [  4,   4,   2,   4],
        [  0, 100,   3,   3],
        [  2,   4,   3,   2]])

# 51. Pointwise operation where the dimension is not changed

In [75]:
# add

torch.add(torch.randn((16, 4)), torch.randn((16, 4))).size()

torch.Size([16, 4])

In [76]:
torch.add(torch.randn((16, 4)), torch.randn((4, ))).size()

torch.Size([16, 4])

In [78]:
torch.add(torch.randn((16, 3, 128, 128)), torch.randn((16,128)).unsqueeze(1).unsqueeze(2)).size()

torch.Size([16, 3, 128, 128])

In [79]:
# sub

torch.sub(torch.randn((16, 4)), torch.randn((16, 4))).size()

torch.Size([16, 4])

In [80]:
torch.sub(torch.randn((16, 4)), torch.randn((4, ))).size()

torch.Size([16, 4])

In [81]:
torch.sub(torch.randn((16, 3, 128, 128)), torch.randn((16,128)).unsqueeze(1).unsqueeze(2)).size()

torch.Size([16, 3, 128, 128])

In [ ]:
# The same way all will be done, for instance
'''
1. mul
2. div
3. matmul
'''

# 52. torch.randn_like(), torch.rand_like()

In [82]:
torch.randn_like(torch.randn((16, 3, 128, 128))).size()

torch.Size([16, 3, 128, 128])

In [83]:
torch.rand_like(torch.randn((16, 3, 128, 128))).size()

torch.Size([16, 3, 128, 128])

# Clarification

In [91]:
value, indicies = torch.randn((64, 4)).max(dim = 0) # Column wise: the result: 4
value.size()

torch.Size([4])

In [92]:
value, indicies = torch.randn((64, 4)).max(dim = 1) # Row wise: the result: 64
value.size()

torch.Size([64])

In [93]:
value, indicies = torch.randn((64, 3, 128, 128)).max(dim = 1) # the result: 64, 128, 128
value.size()

torch.Size([64, 128, 128])