In [129]:
import torch
import torch.nn as nn

# 1. torch.tensor

In [130]:
# Create 1D tesnor
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [131]:
type(torch.tensor([1, 2, 3]))

torch.Tensor

In [132]:
# Create 2d tensor
torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [133]:
# Create 3D tensor

torch.tensor([[
    [1, 2, 3],
    [4, 5, 6]
]])

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [134]:
# Create the tensor and show dim
torch.tensor([[
    [1, 2, 3],
    [4, 5, 6]
]]).dim()

3

In [135]:
import numpy as np
np_array = np.array([[1, 2, 3,], [4, 5, 6]])

torch.tensor(data = np_array, dtype = torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# 2. torch.from_numpy()

In [136]:
np_arary = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

torch.from_numpy(np_array)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [137]:
torch.tensor(data = np_array)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [138]:
A = torch.from_numpy(np_array)
B = torch.tensor(data = np_array)

A.eq(B)

tensor([[True, True, True],
        [True, True, True]])

# 3. torch.rand()

In [139]:
# Create the random_variables

# 1D
torch.rand((64, )).size()

torch.Size([64])

In [140]:
# 2D
torch.rand((3, 4), dtype = torch.float32)

tensor([[0.3562, 0.8405, 0.8168, 0.4210],
        [0.2720, 0.5742, 0.3860, 0.8090],
        [0.8918, 0.4823, 0.2892, 0.2260]])

In [141]:
# 3D
torch.rand((64, 3, 64, 64)).size()

torch.Size([64, 3, 64, 64])

# 4. torch.randn()

In [142]:
# 1D - random variables
torch.randn((64, )).size()

torch.Size([64])

In [143]:
# 2D
torch.randn((3, 4)).size()

torch.Size([3, 4])

In [144]:
# 3D
torch.randn((64, 3, 64, 64)).size()

torch.Size([64, 3, 64, 64])

# 5. torch.randint()

In [145]:
# 1D
torch.randint(0, 101, (64, )).size()

torch.Size([64])

In [146]:
# 2D
torch.randint(0, 20, (3, 5)).size()

torch.Size([3, 5])

In [147]:
# 3D
torch.randint(0, 5, (64, 3, 64, 64)).size()

torch.Size([64, 3, 64, 64])

# 6. torch.min()

In [148]:
torch.tensor([1, -2, 3]).min()

tensor(-2)

In [149]:
value, _ = torch.randint(0, 50, (3, 4)).min(dim = 1) # Row wise
value

tensor([7, 2, 3])

In [150]:
value, _ = torch.randint(0, 50, (3, 4)).min(dim = 0) # Column wise
value

tensor([ 1, 11,  4, 15])

In [151]:
value.min()

tensor(1)

# 7. torch.max()

In [152]:
# 1D
torch.full((64, ), 0.01).max()

tensor(0.0100)

In [153]:
# 2D
value, _ = torch.full((3, 4), 0.01).max(dim = 1) # Row
value

tensor([0.0100, 0.0100, 0.0100])

In [154]:
# 3D
value, _ = torch.randn((64, 3, 64, 64)).max(dim = 0)
value.min()

tensor(1.1453)

# 8. torch.mean()

In [155]:
torch.tensor([1, 2, 3], dtype = torch.float).mean()

tensor(2.)

In [156]:
# 2D
torch.randn((3, 4)).mean(dim = 1) # Row

tensor([-0.6005, -0.0610,  0.3530])

In [157]:
torch.randn((1, 3, 1, 1)).mean(dim = 0) # Column wise

tensor([[[-0.5077]],

        [[-0.1322]],

        [[ 1.8512]]])

# 9. torch.std()

In [158]:
torch.randn((3, 4)).std()

tensor(0.8856)

# 10. torch.var()

In [159]:
torch.randn([1, 2, 3], dtype = torch.float).var()

tensor(1.5800)

In [160]:
torch.eye(3).var(dim = 1) # Row wise

tensor([0.3333, 0.3333, 0.3333])

In [161]:
torch.arange(0, 100, 2, dtype=torch.float).view(10, 5).var(dim = 0) # Column  wise

tensor([916.6667, 916.6667, 916.6667, 916.6667, 916.6667])

# 11. torch.size()

In [162]:
torch.linspace(0, 100, 20).size()

torch.Size([20])

In [163]:
torch.rand((3, 4)).size()

torch.Size([3, 4])

In [164]:
torch.randn((64, 3, 64, 64)).size(0)

64

# 12. torch.shape

In [165]:
# 1D
torch.range(0, 100).shape

<ipython-input-165-e0718141ac2a>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 100).shape


torch.Size([101])

In [166]:
torch.zeros((3, 4)).shape[1]

4

In [167]:
torch.ones((64, 3, 64, 64)).shape

torch.Size([64, 3, 64, 64])

# 13. torch.view()

In [168]:
# Do the flatten using -1
torch.randn((64, 3, 32, 32)).view(-1).size()

torch.Size([196608])

In [169]:
# Reshape
torch.zeros((32, )).view(4, 8).size()

torch.Size([4, 8])

# 14. Torch.reshape()

In [170]:
# 1D
torch.tensor([1, 2, 3]).reshape(-1).size()

torch.Size([3])

In [171]:
# 2D tensor
torch.arange(0, 500, 10).reshape(10, 5).shape

torch.Size([10, 5])

# 15. torch.concat()/cat()

In [172]:
A = torch.randn((3, 4))
B = torch.randn(3, 12)

torch.cat((A, B), dim = 1).size()

torch.Size([3, 16])

In [173]:
A = torch.randn((3, 4))
B = torch.randn((4, 4))

torch.cat((A, B), dim = 0).size()

torch.Size([7, 4])

In [174]:
A = torch.randn((64, 3, 32, 32))
B = torch.randn((64, 3, 32, 32))

torch.cat((A, B), dim = 1).size()

torch.Size([64, 6, 32, 32])

In [175]:
A = torch.randn((64, 3, 32, 32))
B = torch.randn((32, 3, 32, 32))

torch.cat((A, B), dim = 0).size()

torch.Size([96, 3, 32, 32])

# Torch.linspace()

In [176]:
torch.linspace(0, 100, 20).size()

torch.Size([20])

# 18. torch.arange()

In [177]:
torch.arange(0, 20, 1).size()

torch.Size([20])

# 19. torch.logspace()

In [178]:
torch.logspace(0, 100, 20).view(2, 1, 10).size()

torch.Size([2, 1, 10])

# 20. torch.zeros()

In [179]:
# 1D
torch.zeros((64, )).size()

torch.Size([64])

In [180]:
#2D
torch.zeros((3, 4)).size()

torch.Size([3, 4])

In [181]:
# 3D
torch.zeros((64, 3, 64, 64)).size()

torch.Size([64, 3, 64, 64])

# 21. torch.ones()

In [182]:
torch.ones((32, )).size()

torch.Size([32])

In [183]:
torch.ones((3, 4)).size()

torch.Size([3, 4])

In [184]:
torch.ones((32, 1, 32, 32)).size()

torch.Size([32, 1, 32, 32])

# 22. torch.full()

In [185]:
# 1D
torch.full((64, ), 0.01).size()

torch.Size([64])

In [186]:
# 2D
torch.full((3, 4), -.01)

tensor([[-0.0100, -0.0100, -0.0100, -0.0100],
        [-0.0100, -0.0100, -0.0100, -0.0100],
        [-0.0100, -0.0100, -0.0100, -0.0100]])

In [187]:
# 3D
torch.full((64, 3, 32, 32), 0.01).size()

torch.Size([64, 3, 32, 32])

# 23. torch.unbind()

In [188]:
torch.randn((3, 4)).unbind()

(tensor([ 0.1657, -0.7371,  0.9365,  0.3541]),
 tensor([-0.8140, -2.4358,  1.6971,  0.1182]),
 tensor([-1.2444,  1.0372,  0.3939,  1.4434]))

# 24. torch.pow()

In [189]:
torch.pow(torch.randn((3, 4)), 2)

tensor([[0.0207, 2.8885, 0.0955, 4.3697],
        [4.7660, 1.6560, 2.2351, 0.5868],
        [3.1596, 0.9080, 0.0915, 0.0160]])

# 25. torch.tile()

In [190]:
torch.randn(32, 1, 32, 32).tile(2, 3, 2, 2,).size()

torch.Size([64, 3, 64, 64])

# 26. torch.unsqueeze()

In [191]:
torch.randn(64, 64, 64).unsqueeze(1).size()

torch.Size([64, 1, 64, 64])

# 27. torch.squeeze()

In [192]:
torch.randn((64, 1, 64, 64)).squeeze().size()

torch.Size([64, 64, 64])

In [193]:
torch.randn((64, 1, 1, 1)).squeeze().shape

torch.Size([64])

# 28. torch.eye()

In [194]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [195]:
torch.eye(3, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

# 29. torch.where()

In [196]:
torch.where(torch.tensor([1, 2, 3])%2==0, True, False)

tensor([False,  True, False])

# 30. torch.hstack()

In [197]:
A = torch.randn((64, 3, 64, 64))
B = torch.randn((64, 100, 64, 64))

torch.hstack((A, B)).size()

torch.Size([64, 103, 64, 64])

# 31. torch.vstack()

In [198]:
A = torch.randn((64, 1, 32, 32))
B = torch.randn((64, 1, 32, 32))

torch.vstack((A, B)).size()

torch.Size([128, 1, 32, 32])

# 32. torch.maxpool/nn.maxpool()

In [199]:
torch.max_pool2d(input = torch.randn((64, 3, 64, 64)), kernel_size = 2, stride = 2).size()

torch.Size([64, 3, 32, 32])

In [200]:
pool = nn.MaxPool2d(kernel_size = 2, stride = 2)

pool(torch.randn((64, 3, 64, 64))).size()

torch.Size([64, 3, 32, 32])

# 33. torch.sigmoid()/nn.Sigmoid()

In [201]:
torch.sigmoid(input=torch.randn((64, 64))).size()

torch.Size([64, 64])

In [202]:
sigmoid = nn.Sigmoid()

sigmoid(torch.randn((64, 64))).size()

torch.Size([64, 64])

# 34. torch.softmax()/nn.Softmax()

In [203]:
soft = nn.Softmax(dim = 1)

soft(torch.randn((64, 3, 64, 64))).size()

torch.Size([64, 3, 64, 64])

# 35. torch.norm()

In [204]:
# L1 regularization
torch.norm(torch.randn((64, 3, 64, 64)), p = 1)

tensor(627925.9375)

In [205]:
# L2 regularization
torch.norm(torch.randn((64, 3, 64, 64)), p = 2)

tensor(886.5328)

# 36. torch.abs()

In [206]:
torch.abs(torch.tensor(10) - torch.tensor(20))

tensor(10)

# 37, torch.permute()

In [207]:
# 2D
torch.randn((4, 5)).unsqueeze(1).permute(0, 2, 1).size()

torch.Size([4, 5, 1])

In [208]:
# 3D
torch.randn((64, 3, 64, 64)).permute(0, 2, 3, 1).size()

torch.Size([64, 64, 64, 3])

# 38. torch.argmax()

In [209]:
torch.randn((64, 3, 64, 64)).argmax(dim = 1).size() # Row

torch.Size([64, 64, 64])

In [210]:
torch.randn((64, 3, 64, 64)).argmax(dim = 0).size() # column

torch.Size([3, 64, 64])

# 39. torch.argmin()

In [211]:
torch.randn((3, 4)).argmin(dim= 0) # column

tensor([0, 2, 2, 2])

In [212]:
torch.randn((64, 3, 64, 64)).argmin(dim = 1).size() # row

torch.Size([64, 64, 64])

# 40. torch.sort()

In [213]:
value, indices = torch.sort(torch.randn((3, 4)), dim = 1) # Row
value

tensor([[-1.4203, -0.9201,  0.0459,  0.7679],
        [-0.5866, -0.1736,  0.2872,  1.3056],
        [-0.5507,  0.4988,  1.0418,  1.1432]])

In [214]:
value, indices = torch.sort(torch.randn((3, 4)), dim = 0)
value

tensor([[ 0.0930,  0.1283, -1.8347, -1.0951],
        [ 0.8095,  0.5738, -1.1022, -0.1155],
        [ 0.8167,  1.3621,  0.7993,  1.6206]])

In [215]:
value, indices = torch.sort(torch.randn((3, 4)), dim = 0, descending=True)
value

tensor([[ 0.2078, -0.3021,  0.3297,  1.3867],
        [-1.0176, -0.9930, -0.2384,  1.2793],
        [-1.4133, -1.8492, -2.0562,  0.0577]])

# 41. nn.Embeddings()

In [216]:
emb = nn.Embedding(10, 64)

emb(torch.randint(0, 10, (64, ))).size()

torch.Size([64, 64])

In [217]:
emb(torch.randint(0, 10, (64, 3, 32, 32))).size() # 64, 3, 32, 32, 64

torch.Size([64, 3, 32, 32, 64])

#42. torch.clamp_()

In [218]:
torch.clamp_(torch.tensor([1., 2., 3.]), -1.0, 1.0)

tensor([1., 1., 1.])

# 43. torch.UpSample()/torch.upsample()

In [219]:
up = nn.Upsample(scale_factor = 2, mode = "bilinear", align_corners=False)
up(torch.randn(64, 3, 64, 64)).size()

torch.Size([64, 3, 128, 128])

# 44. torch.PixelShuffle()

In [220]:
shuffle = nn.PixelShuffle(upscale_factor=2)

shuffle(torch.randn(64, 128, 32, 32)).size() # 64, 32, 64, 64

torch.Size([64, 32, 64, 64])