In [5]:
import torch
import numpy as np
import torch.nn as nn

1. torch.tensor / torch.Tensor

In [3]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [4]:
torch.tensor([
    [1, 2, 3],
    [3, 4, 6]
])

tensor([[1, 2, 3],
        [3, 4, 6]])

2. torch.from_numpy()

In [6]:
torch.from_numpy(np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
))

tensor([[1, 2, 3],
        [4, 5, 6]])

3. torch.rand()

In [8]:
torch.rand((64, )).size()

torch.Size([64])

In [9]:
torch.rand((64, 128)).size()

torch.Size([64, 128])

In [10]:
torch.rand((64, 3, 128, 128)).size()

torch.Size([64, 3, 128, 128])

4. torch.randn()

In [11]:
torch.randn((64, )).size()

torch.Size([64])

In [12]:
torch.randn((64, 128)).size()

torch.Size([64, 128])

In [13]:
torch.randn((64, 3, 128, 128)).size()

torch.Size([64, 3, 128, 128])

5. torch.randint()

In [15]:
torch.randint(0, 10, (64, )).size()

torch.Size([64])

In [16]:
torch.randint(9, 10, (64, 128)).size()

torch.Size([64, 128])

In [17]:
torch.randint(0, 10, (64, 3, 128, 128)).size()

torch.Size([64, 3, 128, 128])

6. torch.min()

In [19]:
torch.min(torch.randint(10, 20, (64, )))

tensor(10)

In [25]:
A = torch.randn((64, 3, 128, 128))
print(A.size())
value, _ = torch.min(A, dim = -1)
print(value.size())
value, _ = torch.min(A, dim = 0)
print(value.size()) # 3, 128, 128

torch.Size([64, 3, 128, 128])
torch.Size([64, 3, 128])
torch.Size([3, 128, 128])


7. torch.max()

In [27]:
A = torch.randn((3, 4))
print(torch.max(A))

A = torch.randn((64, 3, 128, 128))
value, _ = torch.max(A, dim = 1)
print(value.size()) # 64, 128, 128

tensor(2.1910)
torch.Size([64, 128, 128])


8. torch.std()

In [28]:
torch.std(torch.randn((64, 3)))

tensor(1.0331)

In [29]:
A = torch.randn((64, 3, 128, 128))
print(torch.std(A, dim = 0).size()) # 3, 128, 128
print(torch.std(A, dim = 1).size()) # 64, 128, 128

torch.Size([3, 128, 128])
torch.Size([64, 128, 128])


9.torch.var()

In [30]:
torch.var(torch.randn((64, )))

tensor(1.2169)

In [32]:
A = torch.randint(0, 10, (64, 3, 128, 128), dtype=torch.float)
print(A.var(dim = 1).size()) # 64, 128, 128

torch.Size([64, 128, 128])


# 10. torch.mean()

In [35]:
torch.mean(torch.randint(0, 10, (64, ), dtype = torch.float))

tensor(4.4531)

In [37]:
A = torch.randint(0, 10, (64, 3, 128, 128), dtype=torch.float)
print(A.mean().size()) # []
print(torch.mean(A, dim = 0).size()) # 3, 128, 128
print(torch.mean(A, dim = -1).size()) # 64, 3, 128

torch.Size([])
torch.Size([3, 128, 128])
torch.Size([64, 3, 128])


11. torch.median()

In [38]:
torch.randn((64, )).median()

tensor(-0.1400)

In [42]:
A = torch.randn((64, 3, 128, 128))
value, _ = torch.median(A, dim = 0)
print(value.size()) # 3, 128, 128
value, _ = A.median(dim = 2)
print(value.size()) # 64, 3, 128

torch.Size([3, 128, 128])
torch.Size([64, 3, 128])


12. torch.size()

In [43]:
torch.randn((64, 3, 128, 128)).size()

torch.Size([64, 3, 128, 128])

In [44]:
print(torch.randn((64, 3, 128, 128)).size(0))
print(torch.randn((64, 3, 128, 128)).size(1))
print(torch.randn((64, 3, 128, 128)).size(2))
print(torch.randn((64, 3, 128, 128)).size(3))

64
3
128
128


13. torch.shape

In [45]:
torch.randn((64, 128)).shape

torch.Size([64, 128])

In [48]:
A = torch.randint(0, 10, (64, 3, 128, 128), dtype = torch.float)
print(A.shape[0])
print(A.shape[1])
print(A.shape[2])
print(A.shape[3])

64
3
128
128


14. torch.view()

In [50]:
A = torch.randn((64, 3, 128, 128))
print(A.view(-1).size())

torch.Size([3145728])


In [51]:
print(A.view(128, 128, 3, 64).size())

torch.Size([128, 128, 3, 64])


15. torch.reshape()

In [58]:
A = torch.full((64, 3, 128, 128), 1e-10)
print(A.reshape(-1).size())
print(A.reshape(64, 128, 128, 3).size())
print(A.reshape(A.size(0), A.size(-1), A.size(-2), A.size(1)).size()) # 64, 128, 128, 3

torch.Size([3145728])
torch.Size([64, 128, 128, 3])
torch.Size([64, 128, 128, 3])


16. torch.cat()

In [59]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((64, 3, 128, 128))

torch.cat((A, B), dim = 1).size() # 64, 6, 128, 128

torch.Size([64, 6, 128, 128])

In [61]:
torch.cat((A, B), dim = 0).size() # 128, 3, 128, 128

torch.Size([128, 3, 128, 128])

In [62]:
A = torch.randn((64, 128))
B = torch.randn((64, 128))

torch.cat((A, B), dim = 1).size() # 64, 256

torch.Size([64, 256])

In [63]:
torch.cat((A, B), dim = 0).size() # 128, 128

torch.Size([128, 128])

17. torch.linespace()

In [64]:
torch.linspace(0, 100, 5).size()

torch.Size([5])

18. torch.logspace()

In [65]:
torch.logspace(0, 10, 4).size()

torch.Size([4])

19.torch.arange()

In [66]:
torch.arange(0, 10, 2).size()

torch.Size([5])

In [67]:
torch.arange(0, 10, 20).size()

torch.Size([1])

20. torch.flatten()

In [68]:
A = torch.randn((64, 3, 128, 128))
print(A.flatten().size())
print(torch.flatten(A).size())

torch.Size([3145728])
torch.Size([3145728])


21. torch.zeros()

In [69]:
print(torch.zeros((64, )).size())
print(torch.zeros((64, 128)).size())
print(torch.zeros((64, 3, 128, 128)).size())

torch.Size([64])
torch.Size([64, 128])
torch.Size([64, 3, 128, 128])


22. torch.ones()

In [71]:
print(torch.ones((64, )).size())
print(torch.ones((64, 128)).size())
print(torch.ones((64, 3, 128, 128)).size())

torch.Size([64])
torch.Size([64, 128])
torch.Size([64, 3, 128, 128])


23. torch.zeros_like()

In [72]:
torch.zeros_like(torch.randn((64, 3, 128, 128))).size()

torch.Size([64, 3, 128, 128])

24. torch.ones_like()

In [73]:
torch.ones_like(torch.full((64, 128), 1e-10)).size()

torch.Size([64, 128])

25. torch.full()

In [80]:
print(torch.full((64, 128), 1e-10).size())
print(torch.full((64, 3, 128, 128), 1e-1).size())

torch.Size([64, 128])
torch.Size([64, 3, 128, 128])


26. torch.unbind()

In [92]:
A = torch.randn((3, 4))
print(A.unbind()[0].size())
print(torch.unbind(A)[1].size())
print(A.unbind()[2].size())

torch.Size([4])
torch.Size([4])
torch.Size([4])


In [95]:
A = torch.randn((64, 3, 128, 128))
print(A.unbind()[0].size())
print(torch.unbind(A)[1].size())
print(A.unbind()[2].size())

torch.Size([3, 128, 128])
torch.Size([3, 128, 128])
torch.Size([3, 128, 128])


27. torch.pow()

In [96]:
torch.pow(torch.randint(0, 10, (4, )), exponent=2)

tensor([ 0,  0,  9, 25])

In [98]:
A = torch.randn((64, 3, 128, 128))
A.pow(exponent=1e-6).size()

torch.Size([64, 3, 128, 128])

28. torch.tile()

In [99]:
A = torch.randint(0, 10, (64, 1, 32, 32))
A.tile(dims = (1, 3, 2, 2)).size() # 64, 3, 64, 64

torch.Size([64, 3, 64, 64])

In [101]:
print(torch.tile(A, dims = (1, 3, 32, 32)).size())

torch.Size([64, 3, 1024, 1024])


29. torch.unsqueeze()

In [102]:
A = torch.randn((64, 128, 128))
print(A.unsqueeze(1).size())
print(A.unsqueeze(0).size())

torch.Size([64, 1, 128, 128])
torch.Size([1, 64, 128, 128])


30. torch.squeeze()

In [103]:
A = torch.randn((64, 1, 128, 128))
print(A.squeeze().size()) # 64, 128, 128

torch.Size([64, 128, 128])


31. torch.eye()

In [105]:
torch.eye(3, 4).size()

torch.Size([3, 4])

In [106]:
torch.eye(3).size()

torch.Size([3, 3])

32. torch.where()

In [109]:
A = torch.randint(0, 10, (16, ))

torch.where(A > 5, 1e-5, A)

tensor([2.0000e+00, 1.0000e+00, 2.0000e+00, 1.0000e-05, 1.0000e-05, 1.0000e-05,
        1.0000e-05, 5.0000e+00, 1.0000e+00, 5.0000e+00, 1.0000e-05, 1.0000e-05,
        0.0000e+00, 1.0000e-05, 2.0000e+00, 4.0000e+00])

33. torch.transpose(INDEX) / t()

In [112]:
A = torch.randn((64, 3, 128, 128))
print(A.transpose(1, -1).size()) # 64, 128, 128, 3

torch.Size([64, 128, 128, 3])


In [114]:
A = torch.randn((4, 6))
print(A.t().size())

torch.Size([6, 4])


34. torch.hstack()

In [115]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((64, 3, 128, 128))

In [116]:
torch.hstack((A, B)).size() # It would work like torch.cat() where dim = 1

torch.Size([64, 6, 128, 128])

35. torch.vstack()

In [117]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((64, 3, 128, 128))

In [118]:
torch.vstack((A, B)).size() # 128, 3, 128, 128

torch.Size([128, 3, 128, 128])

36. torch.sigmoid()

In [120]:
A = nn.Sigmoid()
print(A(torch.randn((64, 4))).size()) # 64, 4

torch.Size([64, 4])


37. torch.softmax()

In [121]:
torch.softmax(torch.randn((64, 4)), dim = 1).size()

torch.Size([64, 4])

In [122]:
A = nn.Softmax(dim = 1)
A(torch.randn(64, 4)).size()

torch.Size([64, 4])

In [123]:
A = nn.Softmax(dim = -1)
A(torch.randn(64, 3, 128)).size()

torch.Size([64, 3, 128])

38. torch.norm()

In [124]:
torch.norm(torch.randn((64, 4)), dim = 1).size() # 64

torch.Size([64])

In [126]:
torch.norm(torch.randn((64, 3, 128, 128)), dim = -1).size() # 64, 3, 128

torch.Size([64, 3, 128])

39. torch.abs()

In [129]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((64, 3, 128, 128))
torch.abs((A - B)).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

40. torch.maxpool2D()

In [130]:
torch.max_pool2d(torch.randn((64, 3, 128, 128)), stride = 2, kernel_size = 2).size()

torch.Size([64, 3, 64, 64])

In [131]:
A = nn.MaxPool2d(kernel_size = 2, stride = 2)
print(A(torch.randn((64, 3, 128, 128))).size())

torch.Size([64, 3, 64, 64])


41. torch.permute()

In [134]:
A = torch.randn((64, 3, 128, 128))

In [136]:
torch.permute(A, (0, 2, 3, 1)).size()

torch.Size([64, 128, 128, 3])

In [137]:
A.permute(0, 2, 3, 1).size()

torch.Size([64, 128, 128, 3])

42. torch.argmax()

In [140]:
A = torch.randn((64, 4))
A = torch.softmax(A, dim = 1)
print(A.size())
print(torch.argmax(A, dim = 1).size())
print(A.argmax(dim=1).size()) # 64

torch.Size([64, 4])
torch.Size([64])
torch.Size([64])


43. torch.argmin()

In [142]:
A = torch.randn((64, 128))
A = torch.softmax(A, dim = -1)
A = torch.argmin(A, dim = -1)
A = torch.randn((64, 128))
B = A.argmin(dim = -1)

print(A.size(), B.size())

torch.Size([64, 128]) torch.Size([64])


44. torch.embeddings()

In [143]:
A = nn.Embedding(num_embeddings=10, embedding_dim=512)

print(A(torch.randint(0, 10, (64, ))).size())
print(A(torch.randint(0, 10, (64, 128))).size())

torch.Size([64, 512])
torch.Size([64, 128, 512])


45. torch.sort()

In [144]:
value, _ = torch.sort(torch.randint(0, 10, (32, )), descending=True)
print(value)

tensor([9, 9, 9, 9, 9, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 5, 4, 4, 3, 3, 3, 3, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 0])


In [145]:
value, _ = torch.sort(torch.randint(0, 10, (32, )), descending=False)
print(value)

tensor([0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6,
        6, 7, 8, 8, 8, 8, 9, 9])


46. torch.clamp_

In [146]:
torch.clamp(torch.randn((64, 3, 128, 128)), min = 1e-5, max = 1.0).size()

torch.Size([64, 3, 128, 128])

In [148]:
A = torch.randn((64, 3, 128, 128))
print(A.clamp_(min = 1.0, max = 1000).size())

torch.Size([64, 3, 128, 128])


47. torch.upscale()

In [154]:
A = nn.Upsample(align_corners=False, mode="bilinear", scale_factor=2)
print(A(torch.randn((64, 3, 32, 32))).size())

torch.Size([64, 3, 64, 64])


48. torch.pixelshuffle()

In [155]:
A = nn.PixelShuffle(upscale_factor=2)
A(torch.randn((64, 16, 32, 32))).size() # 64, 4, 64, 64

torch.Size([64, 4, 64, 64])

49. torch.chunk()

In [156]:
chunk1, chunk2, chunk3, chunk4 = torch.chunk(torch.randn((64, 3, 16, 16)), chunks=4, dim = -1)

print(chunk1.size())
print(chunk2.size())
print(chunk3.size())
print(chunk4.size())

torch.Size([64, 3, 16, 4])
torch.Size([64, 3, 16, 4])
torch.Size([64, 3, 16, 4])
torch.Size([64, 3, 16, 4])


50. torch.triu(...., diagonal = 0/1)

In [157]:
torch.triu(torch.randn(3, 4), diagonal=0)

tensor([[-1.1507, -0.2345, -1.4698,  0.9172],
        [ 0.0000, -0.1806, -0.9393, -0.1486],
        [ 0.0000,  0.0000, -0.0897,  0.1621]])

In [158]:
torch.triu(torch.randn(3, 4), diagonal=1)

tensor([[ 0.0000,  0.5505,  1.2230, -0.3839],
        [ 0.0000,  0.0000, -0.9918, -1.5316],
        [ 0.0000,  0.0000,  0.0000, -1.4474]])

51. torch.masked_fill()

In [173]:
A = torch.randint(0, 10, (3, 4))
torch.masked_fill(A, A >= 4, 5e4)

tensor([[    3,     3,     1,     2],
        [50000,     3, 50000, 50000],
        [    2, 50000, 50000, 50000]])

52. torch.randn_like()

In [174]:
torch.randn_like(torch.full((64, 3, 128, 128), 1e-100)).size()

torch.Size([64, 3, 128, 128])

53. torch.rand_like()

In [175]:
torch.rand_like(torch.arange(0, 100, 0.01)).size()

torch.Size([10000])

54. torch.add(), sub(), mul(), div(), matmul()

In [176]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((64, 3, 128, 128))

In [178]:
torch.add(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

In [179]:
torch.sub(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

In [180]:
torch.mul(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

In [181]:
torch.div(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

In [182]:
torch.matmul(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

In [183]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((128, )) # If the last dim is same then it can be done

In [184]:
torch.sub(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])

In [189]:
A = torch.randn((64, 3, 128, 128))
B = torch.randn((64, )) # If the last dim is not same then during that time we need to do the broadcasting manually and it can work during that time

B = B.unsqueeze(1).unsqueeze(2).unsqueeze(3)

In [190]:
torch.sub(A, B).size() # 64, 3, 128, 128

torch.Size([64, 3, 128, 128])