In [1]:
import torch

# Create a dummy array

In [2]:
"""
    rand function take the row/ (row + column) & type is torch.Tensor
"""
print(torch.rand(4, 4),'\n')
print(torch.rand(3, 4, 4),'\n')
print(type(torch.rand(4 ,4)))

"""
    Display the dimension. To display this it will take [.ndim] -> number of dimension
"""
print(torch.rand(4, 4).ndim, '\n')

print(torch.rand(3, 4, 4).ndim)

tensor([[0.0231, 0.7095, 0.2891, 0.4397],
        [0.3246, 0.6407, 0.8446, 0.5415],
        [0.7765, 0.1788, 0.8334, 0.6119],
        [0.5206, 0.5552, 0.0793, 0.8039]]) 

tensor([[[0.6970, 0.8722, 0.5310, 0.5874],
         [0.5252, 0.0391, 0.2686, 0.9383],
         [0.8754, 0.1188, 0.4693, 0.6673],
         [0.8512, 0.2618, 0.0812, 0.3020]],

        [[0.5232, 0.1826, 0.7979, 0.6663],
         [0.4260, 0.9745, 0.4333, 0.5308],
         [0.7388, 0.4578, 0.6383, 0.9054],
         [0.2341, 0.1899, 0.9892, 0.2005]],

        [[0.1987, 0.6716, 0.1649, 0.8143],
         [0.2158, 0.7240, 0.2362, 0.5235],
         [0.8652, 0.6716, 0.1782, 0.4680],
         [0.9049, 0.4282, 0.1025, 0.0298]]]) 

<class 'torch.Tensor'>
2 

3


#Create an another array using randn

In [3]:
"""
    Both rand and randn is used to generate the array but their distribution is quite diffrent while generating the data
"""
print(torch.randn(4, 4),'\n')

print(torch.rand(4, 4),'\n')

print(type(torch.rand(4, 4)),'\n')

print(type(torch.randn(4, 4)),'\n')

# Change the Data Type while generating random numbers
"""
    Needless to say that, randn normally gives the float32 value, if we specifically want the Integer value then used `randint`
"""

print(torch.randn(3, 4, 5, dtype = torch.float32),'\n')

tensor([[-1.2460,  0.4189, -2.1429,  1.0735],
        [ 0.0056, -0.4914, -0.3512,  0.6674],
        [ 0.3210, -1.4654,  1.6054,  2.3658],
        [ 0.1264,  1.4006, -0.6416,  0.6950]]) 

tensor([[0.8619, 0.1826, 0.0936, 0.3130],
        [0.2471, 0.8246, 0.9848, 0.7474],
        [0.4385, 0.5259, 0.4947, 0.2753],
        [0.8824, 0.4972, 0.4894, 0.0281]]) 

<class 'torch.Tensor'> 

<class 'torch.Tensor'> 

tensor([[[-6.7708e-01,  1.4994e+00,  1.6086e+00,  2.9788e-01, -3.4883e-02],
         [-1.3312e-01, -3.8702e-01, -1.5333e+00, -1.9935e-01, -1.5333e-01],
         [-1.8882e-03,  1.0527e+00,  1.0657e-01, -2.4752e+00, -2.9150e-01],
         [-8.5877e-01, -4.2836e-01, -7.5100e-01, -1.3254e+00,  2.2767e+00]],

        [[ 4.5993e-01, -1.8417e+00, -2.2001e+00, -7.0435e-02,  1.0666e+00],
         [ 3.8864e-01, -3.2916e-01,  5.7274e-02, -5.4101e-01, -4.9123e-01],
         [ 5.8536e-02, -1.0630e+00,  6.1446e-02,  6.1105e-01,  1.0610e+00],
         [-7.1853e-01, -3.7286e-01, -6.4132e-02,  2.2366e-

#Create an array with randint

In [4]:
"""
    In `randint` first parameters is low, second parameter is high, then size - size means row/(row+column)
"""
print(torch.randint(low = 0, high = 10, size = (4, 5)),'\n'*2)

print(torch.randint(low = 10, high = 100, size = (6, 3, 3)))

tensor([[2, 6, 6, 5, 1],
        [1, 3, 7, 2, 1],
        [0, 1, 2, 9, 4],
        [9, 1, 2, 8, 0]]) 


tensor([[[33, 83, 20],
         [41, 96, 16],
         [40, 16, 73]],

        [[46, 90, 59],
         [83, 75, 95],
         [90, 67, 68]],

        [[84, 86, 73],
         [26, 23, 70],
         [49, 27, 77]],

        [[51, 87, 72],
         [61, 57, 62],
         [60, 20, 44]],

        [[90, 54, 37],
         [72, 37, 99],
         [37, 34, 96]],

        [[61, 35, 48],
         [89, 58, 21],
         [69, 77, 20]]])


#Create an array with all one's

In [5]:
print(torch.ones(4, 5),'\n')

print(torch.ones(3, 5, 4),'\n')

# Change the Data Type
print(torch.ones(3, 4, dtype = torch.int))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


# Create an array with all zero's

In [6]:
print(torch.zeros(5),'\n')

print(torch.zeros(4, 4),'\n')

print(torch.zeros(6, 7, 4))

tensor([0., 0., 0., 0., 0.]) 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0.,

# Do the concat/cat operation

In [7]:
"""
    Concat/cat is same. here, 1 - means column-wise and 0 - means row-wise
"""
torch.manual_seed(42)
print(torch.randn(2, 5), '\n')

print(torch.randn(4, 5), '\n')

# Do the concat with respect to column-wise
print(torch.concat((torch.randn(2, 5),\
                    torch.randn(2, 4)), axis = 1),'\n')

print(torch.cat((torch.randn(2, 5),\
                 torch.randn(2, 5)), axis = 0),'\n')

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
        [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]]) 

tensor([[-0.7581,  1.0783,  0.8008,  1.6806,  0.0349],
        [ 0.3211,  1.5736, -0.8455,  1.3123,  0.6872],
        [-1.0892, -0.3553, -1.4181,  0.8963,  0.0499],
        [ 2.2667,  1.1790, -0.4345, -1.3864, -1.2862]]) 

tensor([[-0.0499,  0.5263, -0.0085,  0.7291,  0.1331, -0.3870,  0.9912,  0.4679,
         -0.2049],
        [ 0.8640, -1.0157, -0.8887,  0.1498, -0.2089, -0.7409,  0.3618,  1.9199,
         -0.2254]]) 

tensor([[-0.3417,  0.3040, -0.6890, -1.1267, -0.2858],
        [-1.0935,  1.1351,  0.7592, -3.5945,  0.0192],
        [ 0.1052,  0.9603, -0.5672, -0.5706,  1.5980],
        [ 0.1115, -0.0392,  1.4112, -0.6556,  0.8576]]) 



#Change the shape

In [8]:
"""
    To change their shape, use `reshape`/'view'.
"""
torch.manual_seed(42)
A = torch.randn(3, 4, 5, dtype = torch.float32)
print(A,'\n')

# I want to make it 2D - row: 3, and column: 20
print(A.reshape(A.shape[0], -1))

tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
         [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
         [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
         [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396]],

        [[-0.7581,  1.0783,  0.8008,  1.6806,  1.2791],
         [ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
         [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
         [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746]],

        [[-1.5576,  0.9956, -0.8798, -0.6011,  0.3672],
         [ 0.1754,  1.3852, -0.4459,  1.4451,  0.8564],
         [ 2.2181,  0.5232,  1.1754,  0.5612, -0.4527],
         [-0.7718, -0.1722,  0.5238,  0.0566,  0.4263]]]) 

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047,
         -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624,
          1.6423, -0.1596, -0.4974,  0.4396],
        [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791,  1.2964,  0.6105,  1.3347,
         -0.2316,  0.0418, -0.2

#Expand the dimension

In [9]:
A = torch.randint(low = 1, high = 20, size = (4, 5))
print(A, '\n')
print(A.ndim,'\n')
print(A.shape,'\n')

"""
    Like np.expand_dims() - in PyTorch we use unsqueeze(data, dim), dim = 1 means column-wise, 0 = means row-wise
"""
# Here, A shape is (4, 5) -> I want to make it (1, 4, 5) - dim = 0
print(torch.unsqueeze(A, dim = 0).shape,'\n')

# Here, A shape is (4, 5) -> I want to make it (4, 1, 5) - dim = 1
print(torch.unsqueeze(A, dim = 1).shape,'\n')

tensor([[ 3, 14, 10, 13,  8],
        [11,  8, 12, 19,  7],
        [14, 15,  6,  7, 12],
        [ 2, 17,  3, 11,  8]]) 

2 

torch.Size([4, 5]) 

torch.Size([1, 4, 5]) 

torch.Size([4, 1, 5]) 



#Aslike np.where()

In [10]:
torch.manual_seed(42)
A = torch.randint(low = 0, high = 4, size = (2, 3), dtype = torch.int)

print(A, '\n')

THESHOLD = 2
print(torch.where(A > THESHOLD, True, False),'\n\n')

# Do the boolean-indexing
print(A[torch.where(A > THESHOLD, True, False)])

tensor([[2, 3, 0],
        [2, 2, 3]], dtype=torch.int32) 

tensor([[False,  True, False],
        [False, False,  True]]) 


tensor([3, 3], dtype=torch.int32)


#Horizontal Split

In [11]:
"""
    In Horizontal Split, split is done with column-wise. hsplit(tensor, int): if int = 2, then when it will be passed in exact 2, it will be splitted based on column
"""
torch.manual_seed(42)

A = torch.randn(2, 4)

print(A, '\n\n\n')

print(torch.hsplit(A, 2))

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]]) 



(tensor([[ 0.3367,  0.1288],
        [-1.1229, -0.1863]]), tensor([[ 0.2345,  0.2303],
        [ 2.2082, -0.6380]]))


#Vertical Split

In [12]:
"""
      In Vertical Split, split is done with row-wise
"""
torch.manual_seed(42)

A = torch.randn(4, 4)

print(A, '\n\n\n')

print(torch.vsplit(A, 2))

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]]) 



(tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047]]), tensor([[-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]]))


#Transpose

In [13]:
torch.manual_seed(42)

A = torch.randn(2, 3)

print(A,'\n\n\n')

print(A.T)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]]) 



tensor([[ 0.3367,  0.2303],
        [ 0.1288, -1.1229],
        [ 0.2345, -0.1863]])


#Sort the tensor

In [14]:
"""
    In torch, after being done the sorting it will return values and indices.
"""
values, indicies = torch.randint(low = 1, high = 5, size = (2, 5)).sort(descending = False)

print(values, '\n\n\n')

print(torch.randint(low = 1, high = 5, size = (2, 5)).sort(descending = True))

tensor([[1, 3, 3, 4, 4],
        [1, 2, 3, 4, 4]]) 



torch.return_types.sort(
values=tensor([[4, 4, 2, 2, 2],
        [4, 4, 2, 1, 1]]),
indices=tensor([[1, 2, 0, 3, 4],
        [1, 2, 0, 3, 4]]))


#Some Mathematical Operation

In [15]:
# ADD
torch.manual_seed(42)
A = torch.randn(2, 3)
B = torch.randn(2, 3)

print(A + B,'\n'*5)

print(torch.add(A, B))

tensor([[ 2.5449, -0.5092,  0.6961],
        [ 0.4977, -0.5880,  0.6230]]) 





tensor([[ 2.5449, -0.5092,  0.6961],
        [ 0.4977, -0.5880,  0.6230]])


In [16]:
# SUB
torch.manual_seed(42)
A = torch.randn(2, 3)
B = torch.randn(2, 3)

print(A - B,'\n'*5)

print(torch.sub(A, B))

tensor([[-1.8715,  0.7668, -0.2272],
        [-0.0370, -1.6578, -0.9957]]) 





tensor([[-1.8715,  0.7668, -0.2272],
        [-0.0370, -1.6578, -0.9957]])


In [17]:
# MULTIPLY
torch.manual_seed(42)
A = torch.randn(2, 3)
B = torch.randn(2, 3)

print(A * B,'\n'*5)

print(torch.mul(A, B))

tensor([[ 0.7435, -0.0822,  0.1082],
        [ 0.0616, -0.6006, -0.1508]]) 





tensor([[ 0.7435, -0.0822,  0.1082],
        [ 0.0616, -0.6006, -0.1508]])


In [18]:
# MEAN
torch.manual_seed(42)
A = torch.randn(2, 3)
B = torch.randn(2, 3)

print(A.mean())

print(B.mean())

tensor(-0.0631)
tensor(0.6072)


In [19]:
# STD
torch.manual_seed(42)
A = torch.randn(2, 3)
B = torch.randn(2, 3)

print(A.std())

print(B.std())

tensor(0.5495)
tensor(0.9270)


In [20]:
# SQRT
torch.manual_seed(42)
A = torch.randn(2, 3)
B = torch.randn(2, 3)

print(torch.sqrt(A))

print(torch.sqrt(B))

tensor([[0.5803, 0.3589, 0.4842],
        [0.4799,    nan,    nan]])
tensor([[1.4860,    nan, 0.6795],
        [0.5171, 0.7314, 0.8996]])


#Convert NumPy to Torch

In [21]:
import numpy as np
import random
A = np.random.randn(3, 4)

print(A,'\n\n')

print(type(A),'\n')


print(torch.from_numpy(A))

print(type(torch.from_numpy(A)))

[[-0.52709517 -0.84266689  1.64491972  0.49378418]
 [-1.41446344  0.05202807 -0.2139749   0.15121291]
 [-0.35987769  0.24148204 -2.50243338 -1.62535717]] 


<class 'numpy.ndarray'> 

tensor([[-0.5271, -0.8427,  1.6449,  0.4938],
        [-1.4145,  0.0520, -0.2140,  0.1512],
        [-0.3599,  0.2415, -2.5024, -1.6254]], dtype=torch.float64)
<class 'torch.Tensor'>


#Convert Torch to NumPy

In [22]:
torch.manual_seed(42)

A = torch.randn(4, 5)

print(A, '\n\n')

print(type(A),'\n\n')

A = A.numpy()

print(A, '\n\n')

print(type(A))

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055, -0.7581],
        [ 1.0783,  0.8008,  1.6806,  0.3559, -0.6866],
        [-0.4934,  0.2415, -0.2316,  0.0418, -0.2516],
        [ 0.8599, -0.3097, -0.3957,  0.8034, -0.6216]]) 


<class 'torch.Tensor'> 


[[ 1.9269153   1.4872841   0.9007172  -2.105521   -0.75813115]
 [ 1.0783176   0.80080056  1.6806206   0.3558599  -0.686623  ]
 [-0.49335635  0.24148779 -0.23162432  0.04175949 -0.2515753 ]
 [ 0.8598585  -0.30972677 -0.3957105   0.80340934 -0.6215954 ]] 


<class 'numpy.ndarray'>


#Generate the Sequence of Numbers

In [23]:
"""
    Using arange(start, end, step, dtype): 1D
"""
torch.arange(start = 0, end = 100, step = 20, dtype = torch.int)

tensor([ 0, 20, 40, 60, 80], dtype=torch.int32)

In [24]:
"""
    Using linspace(start, end, steps, dtype): 1D
"""
torch.linspace(start = 0, end = 100, steps = 20, dtype = torch.int)

tensor([  0,   5,  10,  15,  21,  26,  31,  36,  42,  47,  52,  57,  63,  68,
         73,  78,  84,  89,  94, 100], dtype=torch.int32)