In [1]:
import torch
import torch.nn as nn

# 1. torch.tensor

In [2]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [3]:
torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [-1, -2, -4, -5]
    ])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [-1, -2, -4, -5]])

# 2. tensor.from_numpy()

In [5]:
import numpy as np

numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

torch.from_numpy(numpy_array)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# 3. torch.rand()

In [6]:
torch.rand((64, ))

tensor([0.2879, 0.7074, 0.5927, 0.1065, 0.6812, 0.1596, 0.9077, 0.4218, 0.1269,
        0.0154, 0.0336, 0.0259, 0.1336, 0.7461, 0.3158, 0.9848, 0.5135, 0.0424,
        0.9745, 0.7851, 0.7774, 0.4299, 0.3129, 0.6555, 0.2877, 0.9156, 0.6988,
        0.7501, 0.0225, 0.5706, 0.2309, 0.3715, 0.4577, 0.9540, 0.8458, 0.1157,
        0.9286, 0.2692, 0.0663, 0.4839, 0.2434, 0.7551, 0.6745, 0.1343, 0.9668,
        0.2710, 0.8578, 0.0329, 0.7793, 0.5783, 0.2942, 0.9932, 0.7695, 0.4298,
        0.0473, 0.3777, 0.6348, 0.3552, 0.4711, 0.4534, 0.6343, 0.7969, 0.8647,
        0.7943])

In [7]:
torch.rand((3, 4), requires_grad=False)

tensor([[0.8965, 0.0517, 0.7346, 0.6394],
        [0.9682, 0.3184, 0.1341, 0.0233],
        [0.0444, 0.0658, 0.3449, 0.5379]])

In [8]:
torch.randn((1, 3, 4, 3), requires_grad=True)

tensor([[[[-2.3131,  0.9159,  1.1986],
          [ 0.0098, -0.5621, -0.6733],
          [ 1.4921, -0.7759,  1.6776],
          [-1.1419, -0.9289, -1.2960]],

         [[ 0.5815, -0.1820,  0.3447],
          [-1.2779, -0.0662, -0.7990],
          [ 0.1317, -1.5522, -1.4993],
          [ 0.5688, -1.0296,  0.2322]],

         [[ 0.8314,  0.3032, -2.5463],
          [-0.7366, -0.7238,  0.1896],
          [ 0.3568, -0.0648, -0.9940],
          [ 0.4168,  0.9036,  1.4462]]]], requires_grad=True)

# 4. torch.randn()

In [9]:
torch.randn((32, ))

tensor([ 4.1509e-02, -6.5918e-01,  1.4121e+00, -5.0016e-01, -5.0924e-01,
        -2.6735e-01,  3.2179e-01,  1.1298e+00, -5.2026e-01, -1.2437e+00,
        -5.0593e-01,  1.3510e+00,  1.1401e+00, -9.1875e-01, -1.2874e-01,
         2.5190e+00,  6.9868e-01, -1.1252e+00,  8.5781e-01,  1.5105e+00,
        -1.5110e+00,  3.4401e-02,  7.9755e-04, -3.4918e-01, -6.8996e-01,
        -1.1769e+00,  1.2362e+00,  8.6274e-01,  8.6256e-02, -8.4413e-02,
        -7.4835e-01, -9.4213e-02])

In [10]:
torch.randn((3, 4), requires_grad=False)

tensor([[-0.8908,  1.5100, -0.3919,  0.3033],
        [ 1.3150,  0.8491, -0.5049,  0.1708],
        [-0.5798, -0.4325,  0.9730,  1.3282]])

In [11]:
torch.randn((1, 3, 2, 1)).size()

torch.Size([1, 3, 2, 1])

# 5. torch.randint()

In [12]:
torch.randint(0, 20, (20, ))

tensor([ 1,  9,  0,  9, 18, 14,  7, 12, 18,  3,  1,  6,  6, 15,  4, 18,  5,  7,
        11,  0])

In [13]:
torch.randint(0, 10, (3, 4))

tensor([[4, 2, 2, 1],
        [4, 1, 8, 7],
        [1, 4, 5, 6]])

In [14]:
torch.randint(0, 2, (32, 3, 64, 64)).size()

torch.Size([32, 3, 64, 64])

# 6. torch.min()

In [16]:
torch.randint(0, 10, (32, )).min()

tensor(0)

In [19]:
tensor = torch.randint(0, 10, (2, 4))
print(tensor)
value1, _ = tensor.min(dim = 0) # Column - 4
value2, _ = tensor.min(dim = 1)  # Row - 2

print(value1, value2)

tensor([[2, 3, 4, 3],
        [2, 1, 9, 1]])
tensor([2, 1, 4, 1]) tensor([2, 1])


# 7. torch.max()

In [21]:
torch.randint(0, 10, (32, )).max()

tensor(9)

In [22]:
value, _ = torch.randint(0, 10, (3, 4)).max(dim = 0)
value

tensor([8, 7, 4, 9])

In [23]:
value, _ = torch.randint(0, 10, (3, 4)).max(dim = 1)
value

tensor([5, 5, 7])

In [25]:
value, _ = torch.randn((1, 3, 4, 3)).max(dim = 1)
value

tensor([[[ 1.1840, -0.3923,  1.0294],
         [ 0.9598, -0.0276, -1.0178],
         [ 0.6873,  0.3620, -0.0695],
         [ 0.5820,  0.8694,  1.1276]]])

# 8. torch.mean()

In [28]:
torch.randn((32, )).mean()

tensor(0.1523)

In [29]:
torch.randn((3, 4)).mean(dim = 0) # Column

tensor([ 0.6504,  0.1579,  0.1069, -0.7590])

In [31]:
torch.randn((3, 4)).mean(dim = 1) # ROW

tensor([ 0.1803,  0.0176, -0.4434])

# 9. torch.median()

In [32]:
torch.randn((32, )).median()

tensor(-0.0591)

In [34]:
value, _ = torch.randn((3, 4)).median(dim = 0) # Column
value

tensor([ 0.1355,  0.8060, -0.6115,  0.3586])

In [35]:
value, _ = torch.randn((3, 10)).median(dim = 1) # ROW wise
value

tensor([-0.2348, -0.6503,  0.3515])

# 10. torch.std()

In [36]:
torch.randn((32, )).std()

tensor(1.0402)

In [37]:
torch.randn((3, 4)).std(dim = 0)

tensor([0.1922, 0.3237, 1.0191, 0.4712])

In [38]:
torch.randn((3, 4)).std(dim = 1)

tensor([0.9066, 0.8115, 0.6642])

# 11. torch.var()

In [39]:
torch.randn((32, )).var()

tensor(1.1771)

In [40]:
torch.randn((3, 4)).var(dim = 0) # Column

tensor([1.2631, 1.1273, 0.0493, 1.5603])

In [41]:
torch.randn((100, 4)).var(dim = 1) # ROW

tensor([1.4293, 0.4617, 1.2338, 0.1963, 1.3349, 3.1847, 2.0402, 0.0199, 2.8977,
        0.5044, 0.3453, 0.9861, 0.3256, 1.3929, 0.6540, 1.1251, 0.5934, 0.9349,
        1.0337, 1.4704, 0.7741, 0.3044, 1.2858, 1.4990, 1.9338, 1.2743, 0.0495,
        1.0387, 0.3977, 1.4185, 0.4026, 0.0836, 1.0379, 0.6022, 0.2343, 1.5736,
        0.8461, 4.9572, 1.9052, 0.3283, 0.9430, 0.4349, 0.7785, 2.3819, 1.1562,
        1.3923, 0.8746, 1.8847, 1.2421, 0.5740, 0.5856, 0.1347, 2.2272, 0.2362,
        0.3067, 0.6078, 1.5665, 1.0953, 0.9636, 0.4672, 0.1813, 0.5642, 0.3774,
        1.4603, 1.9402, 0.5999, 0.1471, 0.9097, 0.1990, 0.0166, 0.9149, 0.8285,
        1.4083, 1.0343, 0.2887, 1.7457, 1.6068, 0.5246, 0.8326, 1.3416, 1.0150,
        3.4975, 0.9321, 0.7656, 0.3944, 1.0155, 0.2358, 3.3356, 0.4201, 1.6441,
        1.6900, 2.2173, 2.1161, 1.1722, 0.2270, 0.9282, 1.5661, 1.6803, 0.8901,
        0.7765])

# 12. torch.size()

In [42]:
torch.randn((32, )).size()

torch.Size([32])

In [43]:
torch.randn((3, 4)).size()

torch.Size([3, 4])

In [44]:
torch.randn((64, 3, 128, 128)).size()

torch.Size([64, 3, 128, 128])

In [45]:
torch.randn((64, 3, 128, 128)).size(0), torch.randn((64, 3, 128, 128)).size(1), torch.randn((64, 3, 128, 128)).size(2), torch.randn((64, 3, 128, 128)).size(3)

(64, 3, 128, 128)

# 13. torch.shape

In [47]:
torch.randn((32, )).shape

torch.Size([32])

In [48]:
torch.randint(0, 10, (3, 4)).shape

torch.Size([3, 4])

In [49]:
torch.randint(0, 10, (3, 4)).shape[-2], torch.randint(0, 10, (3, 4)).shape[-1]

(3, 4)

# 14. torch.view()

In [51]:
torch.randn((32, )).view(4, 8)

tensor([[ 0.1176, -1.5417, -0.7072,  0.7718, -0.0225, -0.9214, -0.8569,  0.0078],
        [-0.6288, -0.3703,  0.2088,  0.3321, -0.2647,  0.0927,  0.2509,  1.7455],
        [ 0.4709,  1.8086,  0.1697, -1.2084, -0.7918, -0.1434,  0.1554, -0.2985],
        [ 1.4156, -0.6272, -0.3088,  1.0513, -0.3334, -1.4484,  0.2837,  0.8279]])

In [52]:
torch.randint(0, 10, (4, 5)).view(-1)

tensor([8, 1, 5, 1, 0, 0, 7, 9, 2, 8, 7, 8, 2, 2, 4, 6, 5, 3, 9, 0])

In [56]:
tensor = torch.randint(0, 10, (64, 3, 128, 128))

tensor.view(tensor.size(0), tensor.size(2), tensor.size(3), tensor.size(1)).size()

torch.Size([64, 128, 128, 3])

# 15.torch.reshape()

In [58]:
torch.rand((4, 5)).reshape(-1, 1, 5).size()

torch.Size([4, 1, 5])

In [59]:
torch.randn((4, 4)).reshape(-1)

tensor([-0.7084,  0.7673,  1.0781, -2.0816,  1.3111,  0.3137, -0.5448,  0.3935,
        -1.1664,  0.5169,  0.6165,  0.9459, -0.9768, -1.1498, -0.3106,  0.3427])

In [63]:
torch.rand((1, 3, 64, 64)).reshape(-1, 64 * 3).size()

torch.Size([64, 192])

# 16. torch.cat()/concat()

In [65]:
tensor1 = torch.randn((3, 4))
tensor2 = torch.randn((3, 3))

torch.cat((tensor1, tensor2), dim = 1) # Column wise
torch.cat((tensor1, tensor2), dim = 1).size() # Column wise

torch.Size([3, 7])

In [66]:
tensor1 = torch.randn((1, 3, 128, 128))
tensor2 = torch.randn((31, 3, 128, 128))

torch.cat((tensor1, tensor2), dim = 0).size() # 32, 3, 128, 128

torch.Size([32, 3, 128, 128])

In [67]:
tensor1 = torch.randn((32, 1, 128, 128))
tensor2 = torch.randn((32, 2, 128, 128))

torch.cat((tensor1, tensor2), dim = 1).size()

torch.Size([32, 3, 128, 128])

# 17. torch.linspace()

In [68]:
torch.linspace(0, 100, 20)

tensor([  0.0000,   5.2632,  10.5263,  15.7895,  21.0526,  26.3158,  31.5789,
         36.8421,  42.1053,  47.3684,  52.6316,  57.8947,  63.1579,  68.4211,
         73.6842,  78.9474,  84.2105,  89.4737,  94.7368, 100.0000])

# 18. torch.logspace()

In [69]:
torch.logspace(0, 20, 3).size() # 3

torch.Size([3])

# 19. torch.aranage()

In [70]:
torch.arange(0, 100, 20).size()

torch.Size([5])

In [72]:
torch.arange(0, 20, 100).size() # 1

torch.Size([1])

# 20. torch.flatten()

In [73]:
torch.randn((3, 4)).size()

torch.Size([3, 4])

In [74]:
torch.randn((3, 4)).flatten() # 12

tensor([-1.1507, -1.4161, -0.0726,  0.2527, -0.4816, -0.5236, -0.4865, -0.8100,
         0.5297, -1.5634,  0.9782, -1.3677])

In [76]:
torch.randn((1, 3, 128, 128)).flatten().size()

torch.Size([49152])

# 21. torch.zeros()

In [77]:
torch.zeros((32, ))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
torch.zeros((3, 4)).size()

torch.Size([3, 4])

In [79]:
torch.zeros((1, 3, 128, 128)).size()

torch.Size([1, 3, 128, 128])

# 22. torch.ones()

In [80]:
torch.ones((32, ))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [82]:
torch.ones((1, 3, 128, 128)).size()

torch.Size([1, 3, 128, 128])

# 23. torch.ones_like()

In [83]:
torch.ones_like(torch.randint(0, 10, (64, ))).size()

torch.Size([64])

In [84]:
torch.ones_like(torch.randint(0, 10, (3, 4)))

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [85]:
torch.ones_like(torch.full((1, 3, 128, 128), 0.0001))

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]])

# 24. torch.zeros_like()

In [86]:
torch.zeros_like(torch.randn(4, 2)).size()

torch.Size([4, 2])

In [87]:
torch.zeros_like(torch.randint(0,10, (32, 32, 32))).size()

torch.Size([32, 32, 32])

In [88]:
torch.zeros_like(torch.randint(0,10, (64, 32, 32, 32))).size()

torch.Size([64, 32, 32, 32])

# 25. torch.full()

In [89]:
torch.full((32, ), -1e-2)

tensor([-0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100,
        -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100,
        -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100,
        -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100, -0.0100])

In [90]:
torch.full((3, 4), -1.01)

tensor([[-1.0100, -1.0100, -1.0100, -1.0100],
        [-1.0100, -1.0100, -1.0100, -1.0100],
        [-1.0100, -1.0100, -1.0100, -1.0100]])

In [91]:
torch.full((1, 3, 128, 128), float("inf"))

tensor([[[[inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          ...,
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf]],

         [[inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          ...,
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf]],

         [[inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          ...,
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf],
          [inf, inf, inf,  ..., inf, inf, inf]]]])

# 26. torch.unbind()

In [92]:
torch.randn((3, 4)).unbind() # Tuple

(tensor([-0.0693,  2.0306,  0.0519, -0.1673]),
 tensor([-1.1505,  0.2542,  0.5197,  2.1612]),
 tensor([-0.1325, -0.0031, -0.3239, -0.9847]))

In [96]:
torch.randn((2, 3, 2, 2)).unbind()[0].size()

torch.Size([3, 2, 2])

# 27. torch.tile()

In [97]:
torch.randn((64, 128, 128)).unsqueeze(1).tile(1, 3, 1, 1).size()

torch.Size([64, 3, 128, 128])

In [98]:
torch.randn((64, 3, 32, 32)).tile(1, 1, 4, 4).size()

torch.Size([64, 3, 128, 128])

# 28. torch.pow()

In [100]:
torch.pow(torch.randint(0, 4, (2, )), exponent=2)

tensor([9, 4])

In [102]:
torch.pow(torch.randn((1, 3, 128, 128)), 0.001)

tensor([[[[0.9983, 0.9999, 0.9996,  ...,    nan, 0.9995, 0.9975],
          [1.0006,    nan, 1.0001,  ...,    nan, 0.9978,    nan],
          [   nan,    nan, 0.9992,  ..., 1.0008,    nan, 0.9954],
          ...,
          [0.9968,    nan,    nan,  ...,    nan,    nan,    nan],
          [   nan, 0.9976, 1.0002,  ..., 0.9990,    nan,    nan],
          [0.9997, 1.0002,    nan,  ..., 0.9978,    nan, 1.0004]],

         [[   nan,    nan, 0.9998,  ..., 1.0004, 0.9983, 0.9998],
          [0.9952,    nan,    nan,  ..., 0.9979,    nan,    nan],
          [   nan,    nan, 1.0008,  ..., 0.9998,    nan,    nan],
          ...,
          [   nan, 0.9991,    nan,  ...,    nan,    nan, 0.9997],
          [1.0006, 0.9997, 0.9980,  ..., 1.0002,    nan,    nan],
          [   nan, 1.0004, 0.9998,  ..., 1.0006,    nan,    nan]],

         [[   nan,    nan, 0.9998,  ..., 0.9989, 1.0005, 0.9998],
          [0.9939,    nan,    nan,  ..., 1.0000,    nan,    nan],
          [0.9996,    nan, 0.9987,  ...,  

# 29. torch.unsqueeze()

In [104]:
torch.randn((4, 3)).unsqueeze(0).unsqueeze(-1).size()

torch.Size([1, 4, 3, 1])

In [106]:
torch.randn((4, 3)).unsqueeze(0).unsqueeze(-1).tile(64, 3, 18, 18*3).size()

torch.Size([64, 12, 54, 54])

# torch.squeeze()

In [107]:
torch.randn((3, 4)).squeeze()

tensor([[ 0.1659,  0.2778,  0.8561,  0.1979],
        [-1.3544, -1.1631,  0.6175, -0.4513],
        [-1.4642,  0.6081,  0.8915,  0.7312]])

In [109]:
torch.full((1, 3, 64, 64), 0.01).squeeze().size()

torch.Size([3, 64, 64])

In [110]:
torch.full((1, 3, 64, 64, 1, 1, 1), 0.01).squeeze().size()

torch.Size([3, 64, 64])

# 31. torch.eye()

In [111]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [112]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# 32. torch.where()

In [114]:
torch.where(torch.randint(0, 10, (4, 6)) > 4, True, False)

tensor([[False,  True,  True,  True, False,  True],
        [ True, False, False, False,  True,  True],
        [False,  True, False,  True, False,  True],
        [False,  True,  True,  True,  True, False]])

In [115]:
result = torch.sigmoid(torch.randn((1, 3, 128, 128)))

torch.where(result > 0.5, 1, 0)

tensor([[[[0, 1, 0,  ..., 1, 1, 1],
          [0, 0, 1,  ..., 0, 0, 1],
          [1, 1, 1,  ..., 0, 1, 1],
          ...,
          [0, 0, 0,  ..., 0, 0, 1],
          [0, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 1, 0]],

         [[0, 1, 1,  ..., 0, 1, 0],
          [0, 0, 0,  ..., 1, 0, 0],
          [1, 0, 1,  ..., 0, 1, 1],
          ...,
          [1, 1, 1,  ..., 1, 0, 1],
          [1, 1, 0,  ..., 0, 1, 1],
          [1, 0, 1,  ..., 0, 1, 1]],

         [[1, 0, 0,  ..., 1, 1, 0],
          [1, 0, 1,  ..., 1, 0, 1],
          [0, 1, 0,  ..., 1, 0, 0],
          ...,
          [0, 1, 1,  ..., 0, 1, 1],
          [1, 0, 1,  ..., 1, 1, 1],
          [1, 0, 1,  ..., 1, 1, 0]]]])

# 33. torch.tanspose()

In [118]:
torch.randn((3, 4)).t().size()

torch.Size([4, 3])

In [119]:
torch.randn((1, 128, 64, 128)).transpose(1, 2).size() # 1, 64, 128, 128

torch.Size([1, 64, 128, 128])

In [120]:
torch.randn((1, 3, 128, 64)).transpose(-1, -2) # 1, 3, 64, 128
torch.randn((1, 3, 128, 64)).transpose(-1, -2).tile(1, 1, 2, 1).size() # 1, 3, 128, 128

torch.Size([1, 3, 128, 128])

# 34. torch.stack()

In [121]:
tensor1 = torch.randn((3, 4))
tensor2 = torch.randn((3, 60))

torch.hstack((tensor1, tensor2)).size()

torch.Size([3, 64])

# 35. torch.vstack()

In [122]:
tensor1 = torch.full((1, 3, 128, 128), 0.000001)
tensor2 = torch.full((61, 3, 128, 128), 0.01)

torch.vstack((tensor1, tensor2)).size()

torch.Size([62, 3, 128, 128])

# 36. maxpool2d

In [124]:
torch.max_pool2d(torch.randn((1, 3, 128, 128)), kernel_size=2, stride = 2).size()

torch.Size([1, 3, 64, 64])

In [126]:
A = nn.MaxPool2d(kernel_size=2, stride = 2)

A(torch.randn(1, 3, 128, 128)).size()

torch.Size([1, 3, 64, 64])

# 37. torch.sigmoid()

In [127]:
torch.sigmoid(torch.randn((1, 3, 128, 128))).size()

torch.Size([1, 3, 128, 128])

In [128]:
A = nn.Sigmoid()

A(torch.randn((1, 3, 128, 128))).size()

torch.Size([1, 3, 128, 128])

# 38. softmax()

In [129]:
torch.softmax(torch.randn((1, 3, 128, 128)), dim = 1).size()

torch.Size([1, 3, 128, 128])

In [130]:
torch.softmax(torch.randn((1, 3, 128, 128)), dim = 0).size()

torch.Size([1, 3, 128, 128])

In [131]:
A = nn.Softmax(dim = 1)

A(torch.randn((1, 3, 128, 128))).size()

torch.Size([1, 3, 128, 128])

# 39. torch.norm()

In [132]:
torch.norm(torch.randn((3, 4)), p = 1)

tensor(8.5281)

In [135]:
torch.norm(torch.randn((1, 3, 64, 64)), p = 1, dim = 1).size()

torch.Size([1, 64, 64])

In [136]:
torch.norm(torch.randn((1, 3, 64, 64)), p = 1, dim = 0).size()

torch.Size([3, 64, 64])

# 40. torch.abs()

In [137]:
torch.abs(torch.randn((1, 3, 64, 64)) - torch.randn((1, 3, 64, 64))).size()

torch.Size([1, 3, 64, 64])

# 41. torch.permute()

In [138]:
torch.randn((1, 3, 64, 64)).permute(0, 2, 3, 1).size()

torch.Size([1, 64, 64, 3])

In [139]:
torch.randn((64, 32)).permute(1, 0).size()

torch.Size([32, 64])

# 42. torch.argmax()

In [140]:
torch.argmax(torch.randn((3, 4)))

tensor(5)

In [141]:
torch.argmax(torch.randn((3, 4)), dim = 1) # ROW

tensor([2, 2, 3])

In [142]:
torch.argmax(torch.randn((3, 4)), dim = 0) # Column

tensor([1, 1, 1, 1])

In [144]:
torch.argmax(torch.randn((64, 3, 128, 128)), dim = 1).size() # ROW - (64, 128, 128)

torch.Size([64, 128, 128])

In [145]:
torch.argmax(torch.randn((64, 3, 128, 128)), dim = 1).size() # Column - (3, 128, 128)

torch.Size([64, 128, 128])

# 43.torch.argmin()

In [146]:
torch.argmin(torch.randn((3, 4)))

tensor(3)

In [147]:
torch.argmin(torch.randn((1, 3, 4, 4)), dim = 0).size() # Column - (3, 4, 4)

torch.Size([3, 4, 4])

In [148]:
torch.argmin(torch.randn((1, 3, 4, 4)), dim = 1).size() # ROW - (1, 4, 4)

torch.Size([1, 4, 4])

# 44. embeddings

In [153]:
torch.embedding(torch.randint(0, 10, (64, )), 10, 512).size() # 64, 512

In [154]:
A = nn.Embedding(10, 512)

A(torch.randint(0, 10, (64, ))).size()

torch.Size([64, 512])

In [159]:
A = nn.Embedding(10, 512)

A(torch.randint(0, 10, (1, 64, 512))).size()

torch.Size([1, 64, 512, 512])

# 45. torch.sort()

In [161]:
value, _ = torch.sort(torch.randn((4, )), descending=True)
value

tensor([1.9457, 1.6279, 1.3047, 0.5731])

In [162]:
value, _ = torch.sort(torch.randn((4, )), descending=False)
value

tensor([-1.4018, -1.0059,  0.4816,  1.1820])

In [174]:
value, _ = torch.sort(torch.randn((1, 3, 64, 64)), descending = True, dim =1) # ROW 1, 3, 64, 64
value.size()

torch.Size([1, 3, 64, 64])

In [176]:
value, _ = torch.sort(torch.randn((1, 3, 64, 64)), descending = True, dim =0) # Column 1, 3, 64, 64
value.size()

torch.Size([1, 3, 64, 64])

# 46. torch.clamp_

In [182]:
torch.clamp_(torch.randn((3, 4)), min=-0.000001, max =.000001)

tensor([[ 1.0000e-06,  1.0000e-06, -1.0000e-06, -1.0000e-06],
        [ 1.0000e-06, -1.0000e-06,  1.0000e-06, -1.0000e-06],
        [-1.0000e-06,  1.0000e-06, -1.0000e-06,  1.0000e-06]])

# 47. Upsameple

In [183]:
A = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False)

A(torch.randn((1, 3, 128, 128))).size()  # 1, 3, 256, 256

torch.Size([1, 3, 256, 256])

In [184]:
A = nn.Upsample(scale_factor=4, mode="bilinear", align_corners=False)

A(torch.randn((1, 3, 128, 128))).size()  # 1, 3, 512, 512

torch.Size([1, 3, 512, 512])

# 48. pixel_shuffle()

In [186]:
torch.pixel_shuffle(torch.randn((1, 64, 32, 32)), 2).size()

torch.Size([1, 16, 64, 64])

In [187]:
torch.randn((1, 64, 32, 32)).view(-1).size(), torch.pixel_shuffle(torch.randn((1, 64, 32, 32)), 2).view(-1).size()

(torch.Size([65536]), torch.Size([65536]))

In [188]:
A = nn.PixelShuffle(upscale_factor=4)

A(torch.randn((1, 16, 8, 8))).size()

torch.Size([1, 1, 32, 32])

In [189]:
torch.randn((1, 16, 8, 8)).view(-1).size(), A(torch.randn((1, 16, 8, 8))).flatten().size()

(torch.Size([1024]), torch.Size([1024]))

# 49. torch.chunk()

In [196]:
tensor1, tensor2, tensor3, tensor4 = torch.full((16, 16), 0.001).chunk(4, dim = -1)

tensor1.size(), tensor2.size(), tensor3.size(), tensor4.size()

(torch.Size([16, 4]),
 torch.Size([16, 4]),
 torch.Size([16, 4]),
 torch.Size([16, 4]))

In [198]:
tensor1, tensor2 = torch.chunk((torch.randint(0, 10, (1, 3, 64, 16))), 2, dim = -2)

tensor1.size(), tensor2.size()

(torch.Size([1, 3, 32, 16]), torch.Size([1, 3, 32, 16]))

# 50. torch.triu()

In [200]:
torch.triu(torch.ones_like(torch.randn(4, 5)), diagonal=0)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.]])

In [204]:
result = torch.triu(torch.ones_like(torch.randn(4, 5)), diagonal=1)

torch.where(result == 0., 1., 0.)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.]])

In [205]:
torch.triu(torch.ones((3, 4)), diagonal=-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 1., 1., 1.]])

# 51. masked_fill()

In [221]:
tensor = torch.randint(1, 10, (10, 4))
torch.masked_fill(tensor, tensor == 3, 1000001)

tensor([[      1,       5,       9,       8],
        [      1, 1000001,       9,       4],
        [      9,       6,       4,       4],
        [      2,       2,       8, 1000001],
        [      6,       7,       5,       1],
        [      2, 1000001, 1000001,       2],
        [      1,       4,       9,       6],
        [      6,       4,       9,       4],
        [      1,       8,       5,       1],
        [      7,       2,       6,       8]])

In [224]:
tensor.masked_fill(tensor == 5, 1001)

tensor([[   1, 1001,    9,    8],
        [   1,    3,    9,    4],
        [   9,    6,    4,    4],
        [   2,    2,    8,    3],
        [   6,    7, 1001,    1],
        [   2,    3,    3,    2],
        [   1,    4,    9,    6],
        [   6,    4,    9,    4],
        [   1,    8, 1001,    1],
        [   7,    2,    6,    8]])

# 52 add, sub, mul, div, matmul

In [225]:
tensor1 = torch.randn((1, 3, 128, 128))
tensor2 = torch.randn((1, 3, 128, 128))

print(torch.add(tensor1, tensor2).size())

print(torch.sub(tensor1, tensor2).size())

print(torch.mul(tensor1, tensor2).size())

print(torch.div(tensor1, tensor2).size())

torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])


In [226]:
tensor1 = torch.randn((1, 3, 128, 128))
tensor2 = torch.randn((128, ))

print(torch.add(tensor1, tensor2).size())

print(torch.sub(tensor1, tensor2).size())

print(torch.mul(tensor1, tensor2).size())

print(torch.div(tensor1, tensor2).size())

torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])


In [228]:
tensor1 = torch.randn((1, 3, 128, 128))
tensor2 = torch.randn((128, ))
tensor2 = tensor2.unsqueeze(0).unsqueeze(1).unsqueeze(2) # 1, 1, 1, 128 # Do the broad casting

print(torch.add(tensor1, tensor2).size())

print(torch.sub(tensor1, tensor2).size())

print(torch.mul(tensor1, tensor2).size())

print(torch.div(tensor1, tensor2).size())

torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 3, 128, 128])


In [231]:
tensor1 = torch.randn((1, 3, 128, 128))
tensor2 = torch.randn((128, ))
tensor2 = tensor2.unsqueeze(0).unsqueeze(1).unsqueeze(2) # 1, 1, 1, 128 # Do the broad casting
tensor2 = tensor2.permute(0, 1, 3, 2)


torch.matmul(tensor1, tensor2).size()

torch.Size([1, 3, 128, 1])

In [233]:
tensor1 = torch.randn((1, 3, 128, 128))
tensor2 = torch.randn((128, ))
tensor2 = tensor2.unsqueeze(0).unsqueeze(1).unsqueeze(2) # 1, 1, 1, 128 # Do the broad casting

(tensor1 * tensor2).size()

torch.Size([1, 3, 128, 128])