In [1]:
import torch

# Torch.tensor

- This will make the data into tensor

In [8]:
data = torch.randint(0, 10, (64, ))
data = torch.tensor(data, dtype = torch.float32)

print(data)

tensor([8., 7., 2., 6., 4., 4., 2., 7., 0., 5., 4., 6., 5., 2., 0., 9., 5., 4.,
        8., 2., 1., 5., 7., 0., 6., 5., 1., 9., 6., 4., 5., 0., 6., 0., 3., 5.,
        8., 0., 3., 8., 6., 8., 0., 9., 4., 6., 0., 3., 1., 3., 8., 7., 5., 3.,
        8., 3., 8., 0., 7., 0., 7., 5., 0., 4.])


<ipython-input-8-58ed05a1dbab>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data = torch.tensor(data, dtype = torch.float32)


In [13]:
row = 4
column = 4

data = torch.eye(row, column)
data = torch.tensor(data = data, dtype = torch.long)

print(data)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])


<ipython-input-13-926a020a37f6>:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data = torch.tensor(data = data, dtype = torch.long)


2. Torch.from_numpy

- That will convert the NumPy array into Tensor

In [17]:
import numpy as np

data_numpy = np.array([[1, 2, 3, 4, 5],
                      [5, 6, 7, 8, 9,],
                      [10, 11, 12, 13, 14]])

print(data_numpy)
print(data_numpy.dtype)

print("_"*50,'\n')

data = torch.from_numpy(data_numpy)

print(data)
print(data.dtype)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
int64
__________________________________________________ 

tensor([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
torch.int64


3. Torch.rand()

- That will return random variables but not in normal distribution

In [20]:
data_1D = torch.rand((10,))

print(data_1D)
print(data_1D.shape,'\n')

data_2D = torch.rand((6, 4))
print(data_2D.shape)

data_ND = torch.rand(64, 3, 64, 64)
print(data_ND.shape)

tensor([0.4951, 0.3279, 0.4474, 0.8746, 0.0197, 0.4494, 0.1943, 0.1035, 0.2338,
        0.6997])
torch.Size([10]) 

torch.Size([6, 4])
torch.Size([64, 3, 64, 64])


4.  Torch.randn()

- That will provide the random variables and it will return the normal distribution of the data

In [21]:
data_1D = torch.randn((64, ))
print(data_1D.shape)

data_2D = torch.randn((4, 5))
print(data_2D.shape)

data_ND = torch.randn(64, 1, 64, 64)
print(data_ND.shape)

torch.Size([64])
torch.Size([4, 5])
torch.Size([64, 1, 64, 64])


5. Torch.randint(start, end, size)

- That will return random variables and it will return the int value

In [25]:
data_1D = torch.randint(low = 0, high = 5, size = (5,))
print(data_1D.shape)

data_2D = torch.randint(low = 0, high = 3, size = (4, 5))
print(data_2D)

data_ND = torch.randint(low = 0, high = 5, size = (3, 1, 3, 4))
print(data_ND)

torch.Size([5])
tensor([[2, 0, 0, 0, 2],
        [0, 0, 0, 1, 2],
        [1, 1, 1, 2, 1],
        [1, 2, 1, 1, 2]])
tensor([[[[1, 1, 1, 1],
          [4, 3, 1, 2],
          [1, 2, 3, 0]]],


        [[[0, 2, 3, 3],
          [4, 0, 1, 4],
          [0, 4, 3, 1]]],


        [[[2, 1, 1, 2],
          [0, 3, 1, 4],
          [1, 0, 0, 0]]]])


6. Torch.min()

- That will return the min value

In [35]:
data = torch.arange(start = 0, end = 11, step = 2)
data = data.reshape(2, 3)

print(data)

print(data.min())

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])
tensor(0)


7. torch.max()

- That will return the maximum value

In [40]:
data = torch.arange(start = 0, end = 100, step = 3)
data = data.reshape((2, data.shape[0]//2))

print(data)

print(data.max())

tensor([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48],
        [51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])
tensor(99)


8. torch.mean()

- that will return the average value

In [48]:
data = torch.randint(0, 5, (10, ), dtype = torch.float32)

print(data)

print(data.mean())

data = torch.randn((3, 4))

print(data)

print(data.mean(dim = 1)) # 1 = Row wise

data = torch.randint(0, 5, (3, 4), dtype = torch.float32)

print(data)

print(data.mean(dim = 0)) # 0 - column wise

tensor([0., 0., 1., 1., 0., 1., 2., 1., 3., 1.])
tensor(1.)
tensor([[ 0.6243,  0.1179, -1.3938, -0.2352],
        [-0.2211,  0.0655,  0.1372,  0.3601],
        [ 0.9583,  2.1311,  1.2468,  0.1893]])
tensor([-0.2217,  0.0854,  1.1314])
tensor([[4., 1., 1., 1.],
        [1., 1., 0., 1.],
        [0., 2., 0., 3.]])
tensor([1.6667, 1.3333, 0.3333, 1.6667])


9. torch.var()

- It will return the variance of the data

In [56]:
data = torch.linspace(0, 10, 12)
data = data.reshape(4, 3)

print(data.var(dim = 1)) # 1- ROW wise
print(data.var(dim = 0)) # 0- COLUMN wise

tensor([0.8264, 0.8264, 0.8264, 0.8264])
tensor([12.3967, 12.3967, 12.3967])


10. torch.std()

- It will return the standard deviation of the data

In [58]:
data = torch.rand((3, 4))

print(data)

print(data.std(dim = 1)) # 1 - ROW wise
print(data.std(dim = 0)) # 0 - Column wise

tensor([[0.5410, 0.2355, 0.9923, 0.1403],
        [0.5840, 0.9787, 0.4355, 0.7424],
        [0.8982, 0.2962, 0.2411, 0.0219]])
tensor([0.3836, 0.2324, 0.3751])
tensor([0.1950, 0.4127, 0.3899, 0.3864])


11. torch.size()

- It will return the shape/size of the dataset

In [61]:
data = torch.rand(3, 4)

print(data)

print(data.size())

print(data.size(0))
print(data.size(1))

tensor([[0.4900, 0.1459, 0.4619, 0.7824],
        [0.1013, 0.3910, 0.7213, 0.5136],
        [0.7766, 0.0721, 0.1772, 0.2134]])
torch.Size([3, 4])
3
4


12. torch.shape

- It will return the shape/size of the dataset

In [62]:
data = torch.logspace(0, 10, 24).reshape(4, 6)

print(data)

print(data.shape)
print(data.shape[0])
print(data.shape[1])

tensor([[1.0000e+00, 2.7213e+00, 7.4057e+00, 2.0153e+01, 5.4844e+01, 1.4925e+02],
        [4.0616e+02, 1.1053e+03, 3.0079e+03, 8.1855e+03, 2.2275e+04, 6.0619e+04],
        [1.6496e+05, 4.4893e+05, 1.2217e+06, 3.3246e+06, 9.0474e+06, 2.4621e+07],
        [6.7002e+07, 1.8233e+08, 4.9619e+08, 1.3503e+09, 3.6747e+09, 1.0000e+10]])
torch.Size([4, 6])
4
6


13. torch.view()

- It is exactly same as reshape

In [66]:
data = torch.arange(start = 0, end = 100, step = 4)

print(data)

data = data.view((5, data.size(0)//5))
print(data)

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
        72, 76, 80, 84, 88, 92, 96])
tensor([[ 0,  4,  8, 12, 16],
        [20, 24, 28, 32, 36],
        [40, 44, 48, 52, 56],
        [60, 64, 68, 72, 76],
        [80, 84, 88, 92, 96]])


14. torch.concat()/torch.cat() with dim = 0/1

- It will merge the multiple tensor

In [85]:
data1 = torch.randint(1, 100, (24,)).view((4, 6))

print(data1.shape)

data2 = torch.randn((4, 6))

print(data2.shape)

data3 = torch.cat((data1, data2), dim = 1)

print(data3.shape) # (4, 12)


#------------------------------------------------------------------#

data1 = torch.randn(4, 6)

print(data1.shape)

data2 = torch.eye(100, 6)

print(data2.shape)

data3 = torch.cat((data1, data2), dim = 0)

print(data3.shape) # (104, 6)

torch.Size([4, 6])
torch.Size([4, 6])
torch.Size([4, 12])
torch.Size([4, 6])
torch.Size([100, 6])
torch.Size([104, 6])


15. torch.linspace()

- It will return the random variables and return 1D tensor for sure

In [90]:
data = torch.linspace(start = 0.01, end = 0.99, steps = 64)

print(data.shape)

print(data.view(8, data.size(0)//8).shape)

torch.Size([64])
torch.Size([8, 8])


16. torch.logspace(start, end, steps)

- It will return the random varibales using log and return 1D tensor

In [91]:
data = torch.logspace(0.01, 0.99, 24)

print(data.size())

print(data.view(4, 6))

torch.Size([24])
tensor([[1.0233, 1.1288, 1.2451, 1.3735, 1.5151, 1.6713],
        [1.8435, 2.0336, 2.2432, 2.4744, 2.7295, 3.0109],
        [3.3213, 3.6636, 4.0413, 4.4579, 4.9174, 5.4244],
        [5.9835, 6.6003, 7.2807, 8.0312, 8.8591, 9.7724]])


17. torch.arange(start, end, steps)

- It will return random varibales and return 1D tesnor

In [93]:
torch.arange(0, 100, 0.01).shape

torch.Size([10000])

18. torch.zeros()

- It will give a tensor with full zeros

In [94]:
data = torch.zeros((4, ))

print(data.shape)

data = torch.zeros((4, 6))

print(data.shape)

data = torch.zeros((64, 1, 64, 64))

print(data.shape)

torch.Size([4])
torch.Size([4, 6])
torch.Size([64, 1, 64, 64])


19. torch.ones()

- It will return the tensor with full of ones

In [95]:
data = torch.ones((64, ))

print(data.size())

data = torch.ones((4, 6))

print(data.size())

data = torch.ones((3, 1, 64, 64))

print(data.shape)

torch.Size([64])
torch.Size([4, 6])
torch.Size([3, 1, 64, 64])


20. torch.full()

- It will return the tensor with specific value

In [97]:
print(torch.full((64, ), 5))

print(torch.full((4, 6), 0.0009))

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
tensor([[0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009],
        [0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009],
        [0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009],
        [0.0009, 0.0009, 0.0009, 0.0009, 0.0009, 0.0009]])


21. torch.unbind()

- It will split the tensor and return the tuple

In [100]:
data = torch.linspace(0.01, 0.99, 64)
data = data.view(8, 8)

print(data.unbind()[0])
print(data.unbind()[6])

tensor([0.0100, 0.0256, 0.0411, 0.0567, 0.0722, 0.0878, 0.1033, 0.1189])
tensor([0.7567, 0.7722, 0.7878, 0.8033, 0.8189, 0.8344, 0.8500, 0.8656])


22. torch.pow()

- It will return the power of the tensor

In [108]:
data = torch.randint(0, 10, (10, ))

print(torch.pow(data, 2))
print(data.pow(2))

data = torch.arange(0, 10, 1)
data = data.view(2, 5)

print(data.pow(0.001))

tensor([81, 16,  1,  0, 25, 64, 64,  0, 16, 64])
tensor([81, 16,  1,  0, 25, 64, 64,  0, 16, 64])
tensor([[0.0000, 1.0000, 1.0007, 1.0011, 1.0014],
        [1.0016, 1.0018, 1.0019, 1.0021, 1.0022]])


23. torch.sort()

- It will return the sorted value and indicies and use dim 1/0

- 1 means ROW wise
- 0 means Column wise

In [112]:
data = torch.randint(1, 20, (15, ))
sorted_value, _ = data.sort()

print(sorted_value)

data = torch.randint(0, 100, (24, ))
data = data.view(4, 6)

print(data)

value, _ = data.sort(dim = 1, descending=False) # Row wise
print(value)


value, _ = data.sort(dim = 0, descending=False) # Column wise
print(value)

tensor([ 4,  4,  6,  6,  8,  8,  9,  9, 10, 11, 11, 13, 14, 18, 19])
tensor([[90, 94, 18, 72, 10, 74],
        [ 9, 66, 77, 35, 82, 77],
        [23, 22, 59, 95,  8, 25],
        [57, 99, 76, 12, 71, 10]])
tensor([[10, 18, 72, 74, 90, 94],
        [ 9, 35, 66, 77, 77, 82],
        [ 8, 22, 23, 25, 59, 95],
        [10, 12, 57, 71, 76, 99]])
tensor([[ 9, 22, 18, 12,  8, 10],
        [23, 66, 59, 35, 10, 25],
        [57, 94, 76, 72, 71, 74],
        [90, 99, 77, 95, 82, 77]])


24. Torch.unsquueze()

- It will create a new dimension

In [116]:
data = torch.randn((4, 6))
print(data.size())

print(data.unsqueeze(1).shape)

print(data.unsqueeze(0).shape)

print(data.unsqueeze(2).shape)

torch.Size([4, 6])
torch.Size([4, 1, 6])
torch.Size([1, 4, 6])
torch.Size([4, 6, 1])


25. torch.squeeze()

- It will remove the dimension where it has 1

In [120]:
data = torch.logspace(10, 111, 24).reshape(1, 4, 6)

print(data.shape)

print(data.squeeze().shape)

print(data.unsqueeze(2).squeeze().shape)

torch.Size([1, 4, 6])
torch.Size([4, 6])
torch.Size([4, 6])


26. torch.tile()

- It will change the dimension

In [122]:
data = torch.randn(32, 1, 32, 32)

print(data.shape)

print(data.tile(2, 3, 2, 2).shape) # 64, 3, 64, 64

torch.Size([32, 1, 32, 32])
torch.Size([64, 3, 64, 64])


27. torch.eye()

- It will create a tensor (row*column)

In [123]:
data = torch.eye(3)

print(data)

data = torch.eye(3, 3)

print(data)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


28. torch.where()

- Its same as np.where

In [128]:
data = torch.randint(1, 100, (20, )).view(4, 5)

print(data)

mask = torch.where(data%2==0, 1, 0)

print(mask)

tensor([[88, 16, 26, 39, 95],
        [88, 19, 19,  7, 58],
        [74, 35, 87, 31, 92],
        [89, 94, 33, 39, 31]])
tensor([[1, 1, 1, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 0, 0]])


29.torch.transpose()/t

- It will change all the tensor

In [135]:
data = torch.full((20, ), 0.009, dtype = torch.float).view(4, 5)

print(data.shape)
print(data.t().size())

torch.Size([4, 5])
torch.Size([5, 4])


30. torch.hstack()

- It will stack the data like torch.cat() with dim = 1

In [140]:
data1 = torch.randn((10, 4))
data2 = torch.randn((10, 100))

print(torch.cat((data1, data2), dim = 1).shape)

print(torch.hstack((data1, data2)).shape)

torch.Size([10, 104])
torch.Size([10, 104])


31. torch.vstack()

- It will stack the tensor with torch.cat() - dim = 0

In [143]:
data1 = torch.randint(1, 6, (4, 5), dtype = torch.float32)
data2 = torch.full((100, 5), 0.001)

print(torch.cat((data1, data2), dim = 0).shape)
print(torch.vstack((data1, data2)).shape)

torch.Size([104, 5])
torch.Size([104, 5])
